save log on failure

diff --git a/.github/workflows/test-arm-arch.yml b/.github/workflows/test-arm-arch.yml
--- a/.github/workflows/test-arm-arch.yml
+++ b/.github/workflows/test-arm-arch.yml
@@ -248,6 +248,10 @@
                   break
                 else
                   echo "Node is still syncing... waiting 1m before checking again."
+                  if grep -q "AppHash" gaia.log; then
+                    echo "ERROR: AppHash found in log."
+                    exit 1
+                  fi
                   tail -n 20 gaia.log
                   sleep 1m
                 fi
@@ -256,6 +260,14 @@
           - name: Print log
             run: |
               tail -n 100 gaia.log
+
+          - name: Upload log on failure
+            if: failure()
+            uses: actions/upload-artifact@v4
+            with:
+              name: gaia-log-apphash-failure-testnet
+              path: gaia.log
+
 
       Test-mainnet-snapshot:
         runs-on: ubuntu-24.04-arm
@@ -320,7 +332,6 @@
                   # Check if the string "AppHash" is in the log
                   if grep -q "AppHash" gaia.log; then
                     echo "ERROR: AppHash found in log."
-                    cat gaia.log
                     exit 1
                   fi
                   tail -n 20 gaia.log
@@ -331,6 +342,14 @@
           - name: Print log
             run: |
               tail -n 100 gaia.log
+
+          - name: Upload log on failure
+            if: failure()
+            uses: actions/upload-artifact@v4
+            with:
+              name: gaia-log-apphash-failure-mainnet
+              path: gaia.log
+
 
       # Test-testnet-state-sync:
       #   runs-on: ubuntu-24.04-arm
