bump upload artifact

diff --git a/.github/workflows/test-arm-arch.yml b/.github/workflows/test-arm-arch.yml
--- a/.github/workflows/test-arm-arch.yml
+++ b/.github/workflows/test-arm-arch.yml
@@ -98,7 +98,7 @@
       #    upgrade_name: ${{ steps.upgrade.outputs.name }}
       #    binary_source: ${{ steps.binary.outputs.source }}
 
-      Test-chain-start:
+      start-chain:
         runs-on: ubuntu-24.04-arm
         # needs: set-versions
         strategy:
@@ -184,7 +184,7 @@
               tests/test_block_production.sh 127.0.0.1 ${rpc_prefix}$COUNT_WIDTH 5
 
 
-      Test-testnet-snapshot:
+      testnet-snapshot:
         runs-on: ubuntu-24.04-arm
         strategy:
           fail-fast: false
@@ -268,90 +268,7 @@
               name: testnet-failure-snapshot
               path: gaia.log
 
-
-      Test-mainnet-snapshot:
-        runs-on: ubuntu-24.04-arm
-        strategy:
-          fail-fast: false
-        env:
-          BINARY_SOURCE: DOWNLOAD
-          GO_VERSION: 1.25.7
-          GAIA_VERSION: ${{ github.event_name == 'push' && 'v27.2.0' || inputs.gaia-version }}
-        steps:
-          - name: Update PATH
-            run: |
-              mkdir -p $HOME/go/bin
-              echo "$HOME/go/bin" >> $GITHUB_PATH
-          - name: Bypass the grub-efi-arm64-signed package
-            run: sudo apt-mark hold grub-efi-arm64-signed
-          - name: Check out repository code
-            uses: actions/checkout@v6
-          - name: Set up Python
-            uses: actions/setup-python@v6
-            with:
-              python-version: '3.11'
-          - name: Install dependencies
-            run: |
-              python -m pip install --upgrade pip
-              python -m pip install toml-cli
-              sudo apt install aria2 -y
-
-          - name: Start chain
-            env:
-              NODE_HOME: /home/runner/.gaia
-              CHAIN_BINARY: ./gaiad
-              GAS_PRICE: 0.005uatom
-            run: |
-              echo "> Downloading Gaia"
-              wget https://github.com/cosmos/gaia/releases/download/$GAIA_VERSION/gaiad-$GAIA_VERSION-linux-arm64 -O $CHAIN_BINARY
-              chmod +x $CHAIN_BINARY
-              echo "> Initializing node @ $NODE_HOME"
-              $CHAIN_BINARY init provider-node --home $NODE_HOME
-              sed -i -e "/minimum-gas-prices =/ s^= .*^= \"$GAS_PRICE\"^" $NODE_HOME/config/app.toml
-              echo "> Downloading genesis file"
-              wget https://snapshots.polkachu.com/genesis/cosmos/genesis.json -O $NODE_HOME/config/genesis.json
-              echo "> Setting up seeds"
-              toml set --toml-path $NODE_HOME/config/config.toml p2p.seeds "327fb4151de9f78f29ff10714085e347a4e3c836@rpc.cosmos.nodestake.org:666"
-              echo "> Downloading and extracting snapshot"
-              aria2c -x 8 -s 8 https://snapshots.polypore.xyz/cosmoshub-4/latest.tar.lz4
-              lz4 -c -d latest.tar.lz4  | tar -x -C $NODE_HOME
-              echo "> Starting node session."
-              tmux new-session -d -s arm-test "$CHAIN_BINARY start --home $NODE_HOME 2>&1 | tee gaia.log"
-              sleep 10s
-              tail -n 100 gaia.log
-
-          - name: Wait until syncing flag is set to false
-            run: |
-              while true; do
-                syncing=$(curl -s localhost:26657/status | jq -r '.result.sync_info.catching_up')
-                if [ "$syncing" == "false" ]; then
-                  echo "Node has finished syncing!"
-                  break
-                else
-                  echo "Node is still syncing... waiting 1m before checking again."
-                  # Check if the string "AppHash" is in the log
-                  if grep -q "AppHash" gaia.log; then
-                    echo "ERROR: AppHash found in log."
-                    exit 1
-                  fi
-                  tail -n 20 gaia.log
-                  sleep 1m
-                fi
-              done
-
-          - name: Print log
-            run: |
-              tail -n 100 gaia.log
-
-          - name: Upload log on failure
-            if: failure()
-            uses: actions/upload-artifact@v4
-            with:
-              name: mainnet-failure-snapshot
-              path: gaia.log
-
-
-      Test-testnet-state-sync:
+      testnet-state-sync:
         runs-on: ubuntu-24.04-arm
         strategy:
           fail-fast: false
@@ -441,3 +358,83 @@
               name: testnet-failure-state-sync
               path: gaia.log
 
+      mainnet-snapshot:
+        runs-on: ubuntu-24.04-arm
+        strategy:
+          fail-fast: false
+        env:
+          BINARY_SOURCE: DOWNLOAD
+          GO_VERSION: 1.25.7
+          GAIA_VERSION: ${{ github.event_name == 'push' && 'v27.2.0' || inputs.gaia-version }}
+        steps:
+          - name: Update PATH
+            run: |
+              mkdir -p $HOME/go/bin
+              echo "$HOME/go/bin" >> $GITHUB_PATH
+          - name: Bypass the grub-efi-arm64-signed package
+            run: sudo apt-mark hold grub-efi-arm64-signed
+          - name: Check out repository code
+            uses: actions/checkout@v6
+          - name: Set up Python
+            uses: actions/setup-python@v6
+            with:
+              python-version: '3.11'
+          - name: Install dependencies
+            run: |
+              python -m pip install --upgrade pip
+              python -m pip install toml-cli
+              sudo apt install aria2 -y
+
+          - name: Start chain
+            env:
+              NODE_HOME: /home/runner/.gaia
+              CHAIN_BINARY: ./gaiad
+              GAS_PRICE: 0.005uatom
+            run: |
+              echo "> Downloading Gaia"
+              wget https://github.com/cosmos/gaia/releases/download/$GAIA_VERSION/gaiad-$GAIA_VERSION-linux-arm64 -O $CHAIN_BINARY
+              chmod +x $CHAIN_BINARY
+              echo "> Initializing node @ $NODE_HOME"
+              $CHAIN_BINARY init provider-node --home $NODE_HOME
+              sed -i -e "/minimum-gas-prices =/ s^= .*^= \"$GAS_PRICE\"^" $NODE_HOME/config/app.toml
+              echo "> Downloading genesis file"
+              wget https://snapshots.polkachu.com/genesis/cosmos/genesis.json -O $NODE_HOME/config/genesis.json
+              echo "> Setting up seeds"
+              toml set --toml-path $NODE_HOME/config/config.toml p2p.seeds "327fb4151de9f78f29ff10714085e347a4e3c836@rpc.cosmos.nodestake.org:666"
+              echo "> Downloading and extracting snapshot"
+              aria2c -x 8 -s 8 https://snapshots.polypore.xyz/cosmoshub-4/latest.tar.lz4
+              lz4 -c -d latest.tar.lz4  | tar -x -C $NODE_HOME
+              echo "> Starting node session."
+              tmux new-session -d -s arm-test "$CHAIN_BINARY start --home $NODE_HOME 2>&1 | tee gaia.log"
+              sleep 10s
+              tail -n 100 gaia.log
+
+          - name: Wait until syncing flag is set to false
+            run: |
+              while true; do
+                syncing=$(curl -s localhost:26657/status | jq -r '.result.sync_info.catching_up')
+                if [ "$syncing" == "false" ]; then
+                  echo "Node has finished syncing!"
+                  break
+                else
+                  echo "Node is still syncing... waiting 1m before checking again."
+                  # Check if the string "AppHash" is in the log
+                  if grep -q "AppHash" gaia.log; then
+                    echo "ERROR: AppHash found in log."
+                    exit 1
+                  fi
+                  tail -n 20 gaia.log
+                  sleep 1m
+                fi
+              done
+
+          - name: Print log
+            run: |
+              tail -n 100 gaia.log
+
+          - name: Upload log on failure
+            if: failure()
+            uses: actions/upload-artifact@v7
+            with:
+              name: mainnet-failure-snapshot
+              path: gaia.log
