update feemarket logic

diff --git a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
@@ -581,6 +581,7 @@ jobs:
         run: scripts/submit_proposal.sh templates/proposal-feemarket-stateful.json
       - name: _Verify feemarket params
         run: |
+          set +e
           echo "[INFO]: Submit large proposal..."
           json=$($CHAIN_BINARY tx gov submit-proposal templates/proposal-large-summary.json --gas $GAS --gas-prices $GAS_PRICES$DENOM --gas-adjustment $GAS_ADJUSTMENT --from $WALLET_1 --keyring-backend test --home $HOME_1 --chain-id $CHAIN_ID -b sync -y -o json)
           if [ $? -eq 0 ]
@@ -595,15 +596,13 @@ jobs:
             $CHAIN_BINARY --home $HOME_1 q tx $txhash
             proposal_id=$($CHAIN_BINARY q tx $txhash --home $HOME_1 --output json | jq -r '.events[] | select(.type=="submit_proposal") | .attributes[] | select(.key=="proposal_id") | .value')
             $CHAIN_BINARY --home $HOME_1 q gov proposal $proposal_id
+            echo "[ERROR]: Proposal went through"
+            exit 1
           else
             echo "[DEBUG]: json output:"
             echo "$json"
-            echo "[ERROR]: Proposal did not go through"
-            exit 1
+            echo "[PASS]: Proposal did not go through"
           fi
-      # - name: _Verify feemarket params
-      #   run: |
-      #     tests/stateful/test_feemarket.sh
       - name: Submit proposal to update modules params
         run: scripts/submit_proposal.sh templates/proposal-test-update-all-modules.json
       - name: _Verify consensus params prop is set
