debug tx

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -355,6 +355,47 @@ jobs:
         run: $CHAIN_BINARY tx bank send $WALLET_1 $WALLET_4 10000000$DENOM --home $HOME_1 --from $MONIKER_1 --keyring-backend test --gas auto --gas-prices $GAS_PRICES$DENOM --gas-adjustment $GAS_ADJUSTMENT --chain-id $CHAIN_ID -y -b sync
       - name: Wait for 1 block to pass
         run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
+        
+      # DEBUG END TX
+      - name: _TX bank send
+        run: |
+          txhash=$($CHAIN_BINARY tx bank send $WALLET_1 $WALLET_2 $VAL_STAKE_STEP$DENOM --home $HOME_1 --from $MONIKER_1 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
+          echo "[INFO]: txhash: $txhash"
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
+          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
+          echo "[INFO]: Code is: $code"
+          if [ -z $code ]; then
+            echo "[ERROR]: code returned blank, TX was unsuccessful."
+          elif [ $code -ne 0 ]; then
+            echo "[ERROR]: code returned: $code, TX unsuccessful"
+            exit 1
+          fi
+      - name: _TX delegate funds
+        run: |
+          txhash=$($CHAIN_BINARY tx staking delegate $VALOPER_1 $VAL_STAKE$DENOM --home $HOME_1 --from $MONIKER_2 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
+          echo "[INFO]: txhash: $txhash"
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
+          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
+          echo "[INFO]: Code is: $code"
+          if [ -z $code ]; then
+            echo "[ERROR]: code returned blank, TX was unsuccessful."
+          elif [ $code -ne 0 ]; then
+            echo "[ERROR]: code returned: $code, TX unsuccessful"
+            exit 1
+          fi
+      - name: _TX distribution withdraw-rewards
+        run: |
+          txhash=$($CHAIN_BINARY tx distribution withdraw-rewards $VALOPER_1 --home $HOME_1 --from $MONIKER_2 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
+          echo "[INFO]: txhash: $txhash"
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
+          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
+          echo "[INFO]: Code is: $code"
+          if [ -z $code ]; then
+            echo "[ERROR]: code returned blank, TX was unsuccessful."
+          elif [ $code -ne 0 ]; then
+            echo "[ERROR]: code returned: $code, TX unsuccessful"
+            exit 1
+          fi
       # - name: Generate wallets for fee market
       #   run: |
       #     feemarket_wallet1_json=$($CHAIN_BINARY --home $HOME_1 keys add feemarket-1 --output json)
@@ -1553,39 +1594,7 @@ jobs:
             echo "[ERROR]: No insufficient fee from log!"
             exit 1
           fi
-      - name: _TX bank send
-        run: |
-          txhash=$($CHAIN_BINARY tx bank send $WALLET_1 $WALLET_2 $VAL_STAKE_STEP$DENOM --home $HOME_1 --from $MONIKER_1 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
-          echo "[INFO]: txhash: $txhash"
-          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
-          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
-          echo "[INFO]: Code is: $code"
-          if [ $code -ne 0 ]; then
-            echo "[ERROR]: TX unsuccessful"
-            exit 1
-          fi
-      - name: _TX delegate funds
-        run: |
-          txhash=$($CHAIN_BINARY tx staking delegate $VALOPER_1 $VAL_STAKE$DENOM --home $HOME_1 --from $MONIKER_2 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
-          echo "[INFO]: txhash: $txhash"
-          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
-          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
-          echo "[INFO]: Code is: $code"
-          if [ $code -ne 0 ]; then
-            echo "[ERROR]: TX unsuccessful"
-            exit 1
-          fi
-      - name: _TX distribution withdraw-rewards
-        run: |
-          txhash=$($CHAIN_BINARY tx distribution withdraw-rewards $VALOPER_1 --home $HOME_1 --from $MONIKER_2 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
-          echo "[INFO]: txhash: $txhash"
-          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
-          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
-          echo "[INFO]: Code is: $code"
-          if [ $code -ne 0 ]; then
-            echo "[ERROR]: TX unsuccessful"
-            exit 1
-          fi
+      # TX tests
       - name: Stop services
         if: always()
         run: |
