run validator check

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -403,23 +403,23 @@
               source scripts/vars.sh
               tests/test_block_production.sh 127.0.0.1 ${rpc_prefix}$COUNT_WIDTH 5
 
-      #     - name: Validator set checks
-      #       run: |
-      #         source scripts/vars.sh
-      #         export validator_count=10
-      #         export MAX_VALIDATORS=8
-      #         export MAX_PROVIDER_VALIDATORS=5
-      #         python scripts/validator_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --provider-max-vals $MAX_PROVIDER_VALIDATORS --ics-removal-upgrade
-      #         jq '.' validator-check-$UPGRADE_HEIGHT.json
-      #         check_result=$(jq -r '.' validator-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
-      #         echo "Check result: $check_result"
-      #         if [ -z "$check_result" ]; then
-      #           echo "> PASS: Validator set check passed"
-      #         else
-      #           echo "> FAIL: Validator set check failed"
-      #           jq '.' validator-check-$UPGRADE_HEIGHT.json
-      #           exit 1
-      #         fi
+          - name: Validator set checks
+            run: |
+              source scripts/vars.sh
+              export validator_count=10
+              export MAX_VALIDATORS=8
+              export MAX_PROVIDER_VALIDATORS=5
+              python scripts/validator_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --provider-max-vals $MAX_PROVIDER_VALIDATORS --ics-removal-upgrade
+              jq '.' validator-check-$UPGRADE_HEIGHT.json
+              check_result=$(jq -r '.' validator-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
+              echo "Check result: $check_result"
+              if [ -z "$check_result" ]; then
+                echo "> PASS: Validator set check passed"
+              else
+                echo "> FAIL: Validator set check failed"
+                jq '.' validator-check-$UPGRADE_HEIGHT.json
+                exit 1
+              fi
 
       #     - name: Query bank supply
       #       run: |
