params proposal

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -391,31 +391,31 @@
               scripts/upgrade.sh $TARGET_VERSION
               
 
-          - name: Submit ICS proposal
-            run: |
-              source scripts/vars.sh
-              address=$($CHAIN_BINARY keys show proposer --home $whale_home -a)
-              echo "Address: $address"
-              echo "> Querying balances"
-              $CHAIN_BINARY q bank balances $address --home $whale_home -o json | jq '.'
-              echo "> Broadcasting proposal"
-              result=$($CHAIN_BINARY tx broadcast signed-ics-proposal.json --home $whale_home --node http://localhost:$whale_rpc -y -o json)
-              echo "> Broadcast result: $result"
-              txhash=$(echo $result | jq -r '.txhash')
-              raw_log=$(echo $result | jq -r '.raw_log')
-              echo "> Transaction hash: $txhash"
-              echo "> Raw log: $raw_log"
-              sleep $(($COMMIT_TIMEOUT*2))
-              echo "> Querying transaction hash $txhash"
-              # The result of the tx query must result in a "not found" error.
-              query_result=$($CHAIN_BINARY q tx $txhash --home $whale_home -o json 2>&1 || true)
-              echo "> Query result: $query_result"
-              if echo "$query_result" | grep -q "not found"; then
-                echo "> PASS: Transaction not found"
-              else
-                echo "> FAIL: Transaction was found"
-                exit 1
-              fi
+          # - name: Submit ICS proposal
+          #   run: |
+          #     source scripts/vars.sh
+          #     address=$($CHAIN_BINARY keys show proposer --home $whale_home -a)
+          #     echo "Address: $address"
+          #     echo "> Querying balances"
+          #     $CHAIN_BINARY q bank balances $address --home $whale_home -o json | jq '.'
+          #     echo "> Broadcasting proposal"
+          #     result=$($CHAIN_BINARY tx broadcast signed-ics-proposal.json --home $whale_home --node http://localhost:$whale_rpc -y -o json)
+          #     echo "> Broadcast result: $result"
+          #     txhash=$(echo $result | jq -r '.txhash')
+          #     raw_log=$(echo $result | jq -r '.raw_log')
+          #     echo "> Transaction hash: $txhash"
+          #     echo "> Raw log: $raw_log"
+          #     sleep $(($COMMIT_TIMEOUT*2))
+          #     echo "> Querying transaction hash $txhash"
+          #     # The result of the tx query must result in a "not found" error.
+          #     query_result=$($CHAIN_BINARY q tx $txhash --home $whale_home -o json 2>&1 || true)
+          #     echo "> Query result: $query_result"
+          #     if echo "$query_result" | grep -q "not found"; then
+          #       echo "> PASS: Transaction not found"
+          #     else
+          #       echo "> FAIL: Transaction was found"
+          #       exit 1
+          #     fi
 
           - name: Stop consumer chain
             run: |
@@ -587,7 +587,7 @@
               echo "> Querying balances"
               $CHAIN_BINARY q bank balances $address --home $whale_home -o json | jq '.'
               echo "> Broadcasting proposal"
-              result=$($CHAIN_BINARY tx broadcast signed-ics-proposal.json --home $whale_home --node http://localhost:$whale_rpc -y -o json)
+              result=$($CHAIN_BINARY tx broadcast signed-ics-param-proposal.json --home $whale_home --node http://localhost:$whale_rpc -y -o json)
               echo "> Broadcast result: $result"
               txhash=$(echo $result | jq -r '.txhash')
               raw_log=$(echo $result | jq -r '.raw_log')
