check number of consumer signatures

diff --git a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
@@ -508,6 +508,14 @@ jobs:
           else
             echo "[INFO]: Block hash matches. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
           fi
+      - name: Check number of signatures
+        run: |
+          total_signatures=$(curl -s 127.0.0.1:$CON1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
+          if [ $total_signatures != 2 ]
+          then
+            echo "[ERROR]: Unexpected number of validators $total_signatures, expected 2"
+            exit 1
+          fi
       - name: Establish CCV channel for consumer a
         run: |
           screen -XS hermes.service quit || true
@@ -523,8 +531,8 @@ jobs:
           echo "Wait for hermes to start..."
           ( tail -f -n0 $HOME/artifact/hermes.service.log & ) | grep -q "Hermes has started"
           sleep 60
-      # - name: _VSC successful> Interchain Security (Consumer) PSS
-      #   run: tests/stateful/test_ccv.sh
+      - name: _VSC successful> Interchain Security (Consumer) PSS
+        run: tests/stateful/test_ccv.sh
       - name: _IBC transfer successful> Interchain Security (Consumer) PSS
         env:
           CONSUMER_CHAIN_ID: consumera
