do not add denom to allowlist

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -250,39 +250,39 @@
               echo "> Rewards pool:"
               $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
 
-          - name: Add reward denom to allowlist> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh  
-              source scripts/vars_consumer_v640_one.sh
-              client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
-              connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
-              channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
-              scripts/update_consumer_rewards.sh $channel_id
-              sleep $(($COMMIT_TIMEOUT*3))
+          # - name: Add reward denom to allowlist> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh  
+          #     source scripts/vars_consumer_v640_one.sh
+          #     client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
+          #     connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
+          #     channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
+          #     scripts/update_consumer_rewards.sh $channel_id
+          #     sleep $(($COMMIT_TIMEOUT*3))
 
-          - name: _Consumer rewards distribution> ICS v6.4.0
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh
-              client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
-              connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
-              channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
-              ibc_denom=ibc/$(echo -n transfer/$channel_id/$CONSUMER_DENOM | shasum -a 256 | cut -d ' ' -f1 | tr '[a-z]' '[A-Z]')
-              echo "> Denom: $ibc_denom"
-              echo "> Consumer rewards pool balances:"
-              $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
-              echo "> Val1 outstanding rewards:"
-              $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
-              val1_rewards=$(curl -s http://localhost:$whale_api/cosmos/distribution/v1beta1/validators/$VALOPER_1/outstanding_rewards | jq -r '.rewards.rewards')
-              echo "> val1_rewards: $val1_rewards"
-              val1_consumer_rewards=$(echo $val1_rewards | jq -r --arg DENOM "$ibc_denom" '.[] | select(.denom==$DENOM).amount')
-              echo "> val1_consumer_rewards: $val1_consumer_rewards"
-              if [ -z "$val1_consumer_rewards" ]; then
-                echo "FAIL: No consumer rewards distributed to val1."
-                exit 1
-              else
-                echo "PASS: Consumer rewards distributed to val1."
-              fi            
+          # - name: _Consumer rewards distribution> ICS v6.4.0
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh
+          #     client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
+          #     connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
+          #     channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
+          #     ibc_denom=ibc/$(echo -n transfer/$channel_id/$CONSUMER_DENOM | shasum -a 256 | cut -d ' ' -f1 | tr '[a-z]' '[A-Z]')
+          #     echo "> Denom: $ibc_denom"
+          #     echo "> Consumer rewards pool balances:"
+          #     $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
+          #     echo "> Val1 outstanding rewards:"
+          #     $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
+          #     val1_rewards=$(curl -s http://localhost:$whale_api/cosmos/distribution/v1beta1/validators/$VALOPER_1/outstanding_rewards | jq -r '.rewards.rewards')
+          #     echo "> val1_rewards: $val1_rewards"
+          #     val1_consumer_rewards=$(echo $val1_rewards | jq -r --arg DENOM "$ibc_denom" '.[] | select(.denom==$DENOM).amount')
+          #     echo "> val1_consumer_rewards: $val1_consumer_rewards"
+          #     if [ -z "$val1_consumer_rewards" ]; then
+          #       echo "FAIL: No consumer rewards distributed to val1."
+          #       exit 1
+          #     else
+          #       echo "PASS: Consumer rewards distributed to val1."
+          #     fi            
 
           - name: Validator set checks
             run: |
