test no_with_veto

diff --git a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
@@ -779,16 +779,40 @@ jobs:
           then
             echo "[ERROR] Amount is not correct"
             echo "Expected balance should be $expected_balance, bank have $current_balance"
-            exit 1
+            error="1"
           else
             echo "Bank balance matches the caluclated balance"
             echo "Expected balance is $expected_balance and bank have $current_balance"
           fi
 
-
-          # Verify deposit is not burned when no_with_veto passed
+          echo "Verify deposit is not burned when no_with_veto passed"
+          starting_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Starting balance: $starting_balance"
+          echo "[INFO]: Submiting proposal and voting no"
+          scripts/submit_proposal.sh templates/proposal-text.json no_with_veto
+          current_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Balance after no vote: $current_balance"
+          echo "[INFO]: Calculate currect balance"
+          expected_balance=$(echo "$starting_balance - $BASE_FEES - $BASE_FEES" | bc)
+          echo "[DEBUG]: expected_balance: $expected_balance"
+          if [ $expected_balance -ne $current_balance ]
+          then
+            echo "[ERROR] Amount is not correct"
+            echo "Expected balance should be $expected_balance, bank have $current_balance"
+            error="1"
+          else
+            echo "Bank balance matches the caluclated balance"
+            echo "Expected balance is $expected_balance and bank have $current_balance"
+          fi
 
           # Verify deposit is burned when quorum is not reached
+
+          if [ "$error" == "1" ]
+          then
+            exit 1
+          else
+            echo "PASSED!"
+          fi
 
 
 
