start only conb

diff --git a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
@@ -445,167 +445,167 @@ jobs:
         run: tests/test_endpoints_rpc.sh localhost $VAL1_RPC_PORT
       - name: Set up relayer
         run: scripts/stateful/setup_relayer.sh
-      - name: Download consumer chain binaries
-        run: |
-          wget -nv $CONSUMER_CHAIN_BINARY_URL -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY
-          chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY
-          wget -nv $CONSUMER_CHAIN_BINARY_URL_2 -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
-          chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
+      # - name: Download consumer chain binaries
+      #   run: |
+      #     wget -nv $CONSUMER_CHAIN_BINARY_URL -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY
+      #     chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY
+      #     wget -nv $CONSUMER_CHAIN_BINARY_URL_2 -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
+      #     chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
 
-      - name: Installing secondary chain binaries
-        env:
-          START_VERSION: ${{ vars.ICA_CHAIN_GAIA_VERSION }}
-        run: |
-          export CHAIN_BINARY_URL=https://github.com/cosmos/gaia/releases/download/$START_VERSION/gaiad-$START_VERSION-linux-amd64
-          echo "Chain binary URL: $CHAIN_BINARY_URL"
-          echo "Installing secondary chain binary..."
-          wget $CHAIN_BINARY_URL -O $HOME/go/bin/$CHAIN_BINARY_SECONDARY -q
-          chmod +x $HOME/go/bin/$CHAIN_BINARY_SECONDARY
-      - name: Start secondary chain
-        env:
-          CHAIN_BINARY: ${{ vars.CHAIN_BINARY_SECONDARY }}
-          CHAIN_SERVICE: ica-chain.service
-          CHAIN_HOME: /home/runner/.ica-chain
-          CHAIN_ID: ica-chain
-          VAL_STAKE: 100000000
-          API_PORT: 35011
-          GRPC_PORT: 36011
-          RPC_PORT: 37011
-          P2P_PORT: 38011
-          PPROF_PORT: 39011
-          GAS_PRICE: 0.0025
-          MONIKER_RELAYER: ${{ vars.MONIKER_2 }}
-          MNEMONIC_RELAYER: ${{ vars.MNEMONIC_2 }}
-        run: |
-          source ~/env/bin/activate
-          scripts/stateful/start_chain_secondary.sh
-      - name: _ICA chain produces blocks> ica-chain
-        run: tests/test_block_production.sh 127.0.0.1 37011 10
-      - name: Send funds to wallet 4 on ICA chain
-        env:
-          CHAIN_BINARY: ${{ vars.CHAIN_BINARY_SECONDARY }}
-          CHAIN_SERVICE: ica-chain.service
-          CHAIN_HOME: /home/runner/.ica-chain
-        run: |
-          $CHAIN_BINARY tx bank send $WALLET_1 $WALLET_4 10000000$DENOM --home $CHAIN_HOME --from $MONIKER_1 --keyring-backend test --gas $GAS --gas-adjustment  $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM -y
-          sleep 60
-          $CHAIN_BINARY q bank balances $WALLET_4 --home $CHAIN_HOME
-      - name: Establish Connection to ICA chain
-        env:
-          CHAIN_HOME: /home/runner/.val1
-        run: |
-          screen -XS hermes.service quit || true
-          killall hermes || true
-          sleep 1
-          echo "Creating client on host-chain: $CHAIN_ID reference-chain ica-chain"
-          hermes create client --host-chain $CHAIN_ID --reference-chain ica-chain
-          echo "Creating client on host-chain: ica-chain Reference-chain: $CHAIN_ID"
-          hermes create client --reference-chain $CHAIN_ID --host-chain ica-chain
-          sleep 30
-          # client_id=$(hermes --json query clients --host-chain $CHAIN_ID | jq -r '.result[] | select(.chain_id == "ica-chain") | .client_id')
-          # client_id=$($CHAIN_BINARY --home $CHAIN_HOME q ibc client states -o json | jq -r '.client_states[] | select (.client_state.chain_id == "ica-chain") | .client_id')
-          # echo "Client ID is: $client_id"
-          # hermes create connection --a-chain $CHAIN_ID --a-client $client_id --b-client 07-tendermint-0
-          hermes create connection --a-chain ica-chain --b-chain $CHAIN_ID
-          echo "ica-chain connection-0 info:"
-          hermes --json query connection end --chain ica-chain --connection connection-0 | tail -n 1 | jq '.result.counterparty'
-          echo "Starting Hermes"
-          screen -L -Logfile $HOME/artifact/hermes.service.log -S hermes.service -d -m bash $HOME/hermes.service.sh
-          # set screen to flush log to 0
-          screen -r hermes.service -p0 -X logfile flush 0
-          echo "Wait for hermes to start..."
-          ( tail -f -n0 $HOME/artifact/hermes.service.log & ) | grep -q "Hermes has started"
-          sleep 60
-      - name: Test ICA
-        env:
-          ICA_HOME: /home/runner/.ica-chain
-          CHAIN_HOME: /home/runner/.val1
-        run: |
-          tests/stateful/test_ica_controller.sh 
-      - name: Initialize consumer chain a with Interchain Security (Consumer) PSS
-        env:
-          CONSUMER_CHAIN_ID: consumera
-          DOWNTIME_BLOCKS: 20
-          CONSUMER_NEW: true
-          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
-        run: scripts/stateful/init_consumer_2_vals.sh
-      - name: Launch opt-in consumer chain a
-        env:
-          CONSUMER_CHAIN_ID: consumera
-          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
-          PSS_ENABLED: true
-          TOPN: 0
-        run: scripts/stateful/launch_consumer_2_vals_optin.sh v4.x
-      - name: _Opt-in consumer chain produces blocks val1> ICS v4.0.0
-        run: tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 10
-      - name: _Opt-in consumer chain produces blocks val2> ICS v4.0.0
-        run: tests/test_block_production.sh 127.0.0.1 $CON2_RPC_PORT 10
-      - name: Check block hashes on both consumer nodes
-        run: |
-          latest_block=$($CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 status | jq -r '.SyncInfo.latest_block_height')
-          echo "[INFO]: Block height is $latest_block"
-          hash_val1=$(curl -s 127.0.0.1:$CON1_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
-          sleep 6
-          hash_val2=$(curl -s 127.0.0.1:$CON2_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
-          echo "[INFO]: cona1 $hash_val1"
-          echo "[INFO]: cona2 $hash_val1"
-          if [ $hash_val1 != $hash_val2 ]
-          then
-            echo "[ERROR]: Block hash does not match. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
-            exit 1
-          else
-            echo "[INFO]: Block hash matches. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
-          fi
-      - name: Print opt-in consumer tendermint validators
-        env:
-          CONSUMER_CHAIN_ID: consumera
-        run: |
-          echo "[INFO]: $CONSUMER_CHAIN_BINARY q tendermint-validator-set"
-          $CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 q tendermint-validator-set -o json | jq -r '.'
-          # echo "[INFO]: $CHAIN_BINARY q provider has-to-validate"
-          # $CHAIN_BINARY --home $HOME_1 q provider has-to-validate -o json | jq -r '.'
-          echo "[INFO]: $CHAIN_BINARY q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID"
-          $CHAIN_BINARY --home $HOME_1 q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID -o json | jq -r '.'
-      - name: Check number of signatures on consumera
-        run: |
-          total_signatures=$(curl -s 127.0.0.1:$CON1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
-          if [ $total_signatures != 2 ]
-          then
-            echo "[ERROR]: Unexpected number of validators $total_signatures, expected 2"
-            exit 1
-          else
-            echo "Expected correct number of validators: $total_signatures"
-          fi
-      - name: Establish CCV channel for consumer a
-        run: |
-          screen -XS hermes.service quit || true
-          killall hermes || true
-          sleep 1
-          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
-          hermes create connection --a-chain consumera --a-client 07-tendermint-0 --b-client $client_id
-          hermes create channel --a-chain consumera --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
-          echo "Starting Hermes"
-          screen -L -Logfile $HOME/artifact/hermes.service.log -S hermes.service -d -m bash $HOME/hermes.service.sh
-          # set screen to flush log to 0
-          screen -r hermes.service -p0 -X logfile flush 0
-          echo "Wait for hermes to start..."
-          ( tail -f -n0 $HOME/artifact/hermes.service.log & ) | grep -q "Hermes has started"
-          sleep 60
-      - name: _VSC successful> Interchain Security (Consumer) PSS
-        run: tests/stateful/test_ccv.sh
-      - name: _IBC transfer successful> Interchain Security (Consumer) PSS
-        env:
-          CONSUMER_CHAIN_ID: consumera
-        run: |
-          set -x
-          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
-          echo "Client ID: $client_id"
-          connection_id=$(hermes --json query client connections --chain $CHAIN_ID --client $client_id | jq -r '. | select(.result).result[]')
-          echo "Connection ID: $connection_id"
-          channel_id=$(hermes --json query connection channels --chain $CHAIN_ID --connection $connection_id | jq -r '. | select(.result).result[] | select(.port_id=="transfer").channel_id')
-          echo "Channel ID: $channel_id"
-          tests/stateful/test_consumer_ibc_transfer.sh $channel_id 2 $WALLET_1 $WALLET_CONSUMER_1
-          echo "CONSUMERA_CHAN_ID=$channel_id" >> $GITHUB_ENV
+      # - name: Installing secondary chain binaries
+      #   env:
+      #     START_VERSION: ${{ vars.ICA_CHAIN_GAIA_VERSION }}
+      #   run: |
+      #     export CHAIN_BINARY_URL=https://github.com/cosmos/gaia/releases/download/$START_VERSION/gaiad-$START_VERSION-linux-amd64
+      #     echo "Chain binary URL: $CHAIN_BINARY_URL"
+      #     echo "Installing secondary chain binary..."
+      #     wget $CHAIN_BINARY_URL -O $HOME/go/bin/$CHAIN_BINARY_SECONDARY -q
+      #     chmod +x $HOME/go/bin/$CHAIN_BINARY_SECONDARY
+      # - name: Start secondary chain
+      #   env:
+      #     CHAIN_BINARY: ${{ vars.CHAIN_BINARY_SECONDARY }}
+      #     CHAIN_SERVICE: ica-chain.service
+      #     CHAIN_HOME: /home/runner/.ica-chain
+      #     CHAIN_ID: ica-chain
+      #     VAL_STAKE: 100000000
+      #     API_PORT: 35011
+      #     GRPC_PORT: 36011
+      #     RPC_PORT: 37011
+      #     P2P_PORT: 38011
+      #     PPROF_PORT: 39011
+      #     GAS_PRICE: 0.0025
+      #     MONIKER_RELAYER: ${{ vars.MONIKER_2 }}
+      #     MNEMONIC_RELAYER: ${{ vars.MNEMONIC_2 }}
+      #   run: |
+      #     source ~/env/bin/activate
+      #     scripts/stateful/start_chain_secondary.sh
+      # - name: _ICA chain produces blocks> ica-chain
+      #   run: tests/test_block_production.sh 127.0.0.1 37011 10
+      # - name: Send funds to wallet 4 on ICA chain
+      #   env:
+      #     CHAIN_BINARY: ${{ vars.CHAIN_BINARY_SECONDARY }}
+      #     CHAIN_SERVICE: ica-chain.service
+      #     CHAIN_HOME: /home/runner/.ica-chain
+      #   run: |
+      #     $CHAIN_BINARY tx bank send $WALLET_1 $WALLET_4 10000000$DENOM --home $CHAIN_HOME --from $MONIKER_1 --keyring-backend test --gas $GAS --gas-adjustment  $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM -y
+      #     sleep 60
+      #     $CHAIN_BINARY q bank balances $WALLET_4 --home $CHAIN_HOME
+      # - name: Establish Connection to ICA chain
+      #   env:
+      #     CHAIN_HOME: /home/runner/.val1
+      #   run: |
+      #     screen -XS hermes.service quit || true
+      #     killall hermes || true
+      #     sleep 1
+      #     echo "Creating client on host-chain: $CHAIN_ID reference-chain ica-chain"
+      #     hermes create client --host-chain $CHAIN_ID --reference-chain ica-chain
+      #     echo "Creating client on host-chain: ica-chain Reference-chain: $CHAIN_ID"
+      #     hermes create client --reference-chain $CHAIN_ID --host-chain ica-chain
+      #     sleep 30
+      #     # client_id=$(hermes --json query clients --host-chain $CHAIN_ID | jq -r '.result[] | select(.chain_id == "ica-chain") | .client_id')
+      #     # client_id=$($CHAIN_BINARY --home $CHAIN_HOME q ibc client states -o json | jq -r '.client_states[] | select (.client_state.chain_id == "ica-chain") | .client_id')
+      #     # echo "Client ID is: $client_id"
+      #     # hermes create connection --a-chain $CHAIN_ID --a-client $client_id --b-client 07-tendermint-0
+      #     hermes create connection --a-chain ica-chain --b-chain $CHAIN_ID
+      #     echo "ica-chain connection-0 info:"
+      #     hermes --json query connection end --chain ica-chain --connection connection-0 | tail -n 1 | jq '.result.counterparty'
+      #     echo "Starting Hermes"
+      #     screen -L -Logfile $HOME/artifact/hermes.service.log -S hermes.service -d -m bash $HOME/hermes.service.sh
+      #     # set screen to flush log to 0
+      #     screen -r hermes.service -p0 -X logfile flush 0
+      #     echo "Wait for hermes to start..."
+      #     ( tail -f -n0 $HOME/artifact/hermes.service.log & ) | grep -q "Hermes has started"
+      #     sleep 60
+      # - name: Test ICA
+      #   env:
+      #     ICA_HOME: /home/runner/.ica-chain
+      #     CHAIN_HOME: /home/runner/.val1
+      #   run: |
+      #     tests/stateful/test_ica_controller.sh 
+      # - name: Initialize consumer chain a with Interchain Security (Consumer) PSS
+      #   env:
+      #     CONSUMER_CHAIN_ID: consumera
+      #     DOWNTIME_BLOCKS: 20
+      #     CONSUMER_NEW: true
+      #     CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
+      #   run: scripts/stateful/init_consumer_2_vals.sh
+      # - name: Launch opt-in consumer chain a
+      #   env:
+      #     CONSUMER_CHAIN_ID: consumera
+      #     CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
+      #     PSS_ENABLED: true
+      #     TOPN: 0
+      #   run: scripts/stateful/launch_consumer_2_vals_optin.sh v4.x
+      # - name: _Opt-in consumer chain produces blocks val1> ICS v4.0.0
+      #   run: tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 10
+      # - name: _Opt-in consumer chain produces blocks val2> ICS v4.0.0
+      #   run: tests/test_block_production.sh 127.0.0.1 $CON2_RPC_PORT 10
+      # - name: Check block hashes on both consumer nodes
+      #   run: |
+      #     latest_block=$($CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 status | jq -r '.SyncInfo.latest_block_height')
+      #     echo "[INFO]: Block height is $latest_block"
+      #     hash_val1=$(curl -s 127.0.0.1:$CON1_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
+      #     sleep 6
+      #     hash_val2=$(curl -s 127.0.0.1:$CON2_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
+      #     echo "[INFO]: cona1 $hash_val1"
+      #     echo "[INFO]: cona2 $hash_val1"
+      #     if [ $hash_val1 != $hash_val2 ]
+      #     then
+      #       echo "[ERROR]: Block hash does not match. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
+      #       exit 1
+      #     else
+      #       echo "[INFO]: Block hash matches. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
+      #     fi
+      # - name: Print opt-in consumer tendermint validators
+      #   env:
+      #     CONSUMER_CHAIN_ID: consumera
+      #   run: |
+      #     echo "[INFO]: $CONSUMER_CHAIN_BINARY q tendermint-validator-set"
+      #     $CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 q tendermint-validator-set -o json | jq -r '.'
+      #     # echo "[INFO]: $CHAIN_BINARY q provider has-to-validate"
+      #     # $CHAIN_BINARY --home $HOME_1 q provider has-to-validate -o json | jq -r '.'
+      #     echo "[INFO]: $CHAIN_BINARY q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID"
+      #     $CHAIN_BINARY --home $HOME_1 q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID -o json | jq -r '.'
+      # - name: Check number of signatures on consumera
+      #   run: |
+      #     total_signatures=$(curl -s 127.0.0.1:$CON1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
+      #     if [ $total_signatures != 2 ]
+      #     then
+      #       echo "[ERROR]: Unexpected number of validators $total_signatures, expected 2"
+      #       exit 1
+      #     else
+      #       echo "Expected correct number of validators: $total_signatures"
+      #     fi
+      # - name: Establish CCV channel for consumer a
+      #   run: |
+      #     screen -XS hermes.service quit || true
+      #     killall hermes || true
+      #     sleep 1
+      #     client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
+      #     hermes create connection --a-chain consumera --a-client 07-tendermint-0 --b-client $client_id
+      #     hermes create channel --a-chain consumera --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
+      #     echo "Starting Hermes"
+      #     screen -L -Logfile $HOME/artifact/hermes.service.log -S hermes.service -d -m bash $HOME/hermes.service.sh
+      #     # set screen to flush log to 0
+      #     screen -r hermes.service -p0 -X logfile flush 0
+      #     echo "Wait for hermes to start..."
+      #     ( tail -f -n0 $HOME/artifact/hermes.service.log & ) | grep -q "Hermes has started"
+      #     sleep 60
+      # - name: _VSC successful> Interchain Security (Consumer) PSS
+      #   run: tests/stateful/test_ccv.sh
+      # - name: _IBC transfer successful> Interchain Security (Consumer) PSS
+      #   env:
+      #     CONSUMER_CHAIN_ID: consumera
+      #   run: |
+      #     set -x
+      #     client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
+      #     echo "Client ID: $client_id"
+      #     connection_id=$(hermes --json query client connections --chain $CHAIN_ID --client $client_id | jq -r '. | select(.result).result[]')
+      #     echo "Connection ID: $connection_id"
+      #     channel_id=$(hermes --json query connection channels --chain $CHAIN_ID --connection $connection_id | jq -r '. | select(.result).result[] | select(.port_id=="transfer").channel_id')
+      #     echo "Channel ID: $channel_id"
+      #     tests/stateful/test_consumer_ibc_transfer.sh $channel_id 2 $WALLET_1 $WALLET_CONSUMER_1
+      #     echo "CONSUMERA_CHAN_ID=$channel_id" >> $GITHUB_ENV
       - name: Initialize consumer chain B with Interchain Security (Consumer) PSS
         env:
           CONSUMER_CHAIN_ID: consumerb
@@ -725,6 +725,8 @@ jobs:
           echo "[INFO] Optin second validator"
           node_key2=$($CONSUMER_CHAIN_BINARY --home $CONSUMERB_HOME_2 tendermint show-validator)
           $CHAIN_BINARY --home $HOME_2 tx provider opt-in ${{ env.CONSUMER_ID_TOPN }} "$node_key2" --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --from val2 -y
+      - name: Wait for 2 blocks
+        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 2 600
       - name: Check number of signatures on consumerb
         run: |
           total_signatures=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
