disable pre-upgrade validator  check

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -312,23 +312,23 @@
             if: matrix.stop-chain == 'true'
 
 
-          - name: Validator set checks
-            run: |
-              source scripts/vars.sh
-              export validator_count=10
-              export MAX_VALIDATORS=8
-              export MAX_PROVIDER_VALIDATORS=5
-              python scripts/validator_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --provider-max-vals $MAX_PROVIDER_VALIDATORS
-              jq '.' validator-check-$UPGRADE_HEIGHT.json
-              check_result=$(jq -r '.' validator-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
-              echo "Check result: $check_result"
-              if [ -z "$check_result" ]; then
-                echo "> PASS: Validator set check passed"
-              else
-                echo "> FAIL: Validator set check failed"
-                jq '.' validator-check-$UPGRADE_HEIGHT.json
-                exit 1
-              fi
+          # - name: Validator set checks
+          #   run: |
+          #     source scripts/vars.sh
+          #     export validator_count=10
+          #     export MAX_VALIDATORS=8
+          #     export MAX_PROVIDER_VALIDATORS=5
+          #     python scripts/validator_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --provider-max-vals $MAX_PROVIDER_VALIDATORS
+          #     jq '.' validator-check-$UPGRADE_HEIGHT.json
+          #     check_result=$(jq -r '.' validator-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
+          #     echo "Check result: $check_result"
+          #     if [ -z "$check_result" ]; then
+          #       echo "> PASS: Validator set check passed"
+          #     else
+          #       echo "> FAIL: Validator set check failed"
+          #       jq '.' validator-check-$UPGRADE_HEIGHT.json
+          #       exit 1
+          #     fi
 
           - name: Upgrade to v28.0.0 (ICS Removal)
             env:
@@ -605,14 +605,15 @@
           #     source scripts/vars.sh
           #     source scripts/vars_consumer_v640_one.sh  
           #     tests/test_ccv_channel.sh
-          - name: _IBC transfer successful> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh  
-              source scripts/vars_consumer_v640_one.sh 
-              client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
-              connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
-              channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
-              tests/test_consumer_ibc_transfer.sh $channel_id channel-1
+
+          # - name: _IBC transfer successful> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh  
+          #     source scripts/vars_consumer_v640_one.sh 
+          #     client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
+          #     connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
+          #     channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
+          #     tests/test_consumer_ibc_transfer.sh $channel_id channel-1
           
           # - name: _Downtime test> ICS v6.4.0
           #   run: |
