Stateful ratelimit test (#179)

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -228,7 +228,7 @@ jobs:
           latest_block=$(gaiad --home $HOME_1 status | jq -r '.sync_info.latest_block_height')
           echo "[INFO]: Block height is $latest_block"
           hash_val1=$(curl -s 127.0.0.1:$VAL1_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
-          sleep 6
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
           hash_val2=$(curl -s 127.0.0.1:$VAL2_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
           if [ $hash_val1 != $hash_val2 ]
           then
@@ -354,13 +354,6 @@ jobs:
           fi
       - name: _Test vesting accounts
         run: tests/stateful/test_vesting.sh
-      # - name: DEBUG
-      #   if: always() && !cancelled()
-      #   run: |
-      #     while [ ! -f /continue ]
-      #     do
-      #       sleep 1
-      #     done
       - name: _Transactions verified> bank send, delegate, and withdraw rewards
         run: tests/stateful/test_tx.sh
       - name: Send funds to wallet 3
@@ -527,7 +520,7 @@ jobs:
           latest_block=$($CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 status | jq -r '.sync_info.latest_block_height')
           echo "[INFO]: Block height is $latest_block"
           hash_val1=$(curl -s 127.0.0.1:$CON1_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
-          sleep 6
+          tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 1 10
           hash_val2=$(curl -s 127.0.0.1:$CON2_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
           echo "[INFO]: cona1 $hash_val1"
           echo "[INFO]: cona2 $hash_val1"
@@ -586,7 +579,7 @@ jobs:
           sleep 60
       - name: _VSC successful> Interchain Security (Consumer) PSS
         run: tests/stateful/test_ccv.sh
-      - name: _IBC transfer successful> Interchain Security (Consumer) PSS
+      - name: Get consumera chain info
         env:
           CONSUMER_CHAIN_ID: consumera
         run: |
@@ -597,21 +590,34 @@ jobs:
           echo "Connection ID: $connection_id"
           channel_id=$(hermes --json query connection channels --chain $CHAIN_ID --connection $connection_id | jq -r '. | select(.result).result[] | select(.port_id=="transfer").channel_id')
           echo "Channel ID: $channel_id"
-          tests/stateful/test_consumer_ibc_transfer.sh $channel_id 2 $WALLET_1 $WALLET_CONSUMER_1 1000
           echo "CONSUMERA_CHAN_ID=$channel_id" >> $GITHUB_ENV
+      - name: Submit rate limit proposal
+        run: |
+          jq -r ".messages[0].channel_or_client_id=\"${{ env.CONSUMERA_CHAN_ID }}\"" templates/proposal-stateful-rate-limit.json > proposal-cona-rate-limit.json
+          scripts/submit_proposal.sh proposal-cona-rate-limit.json
+          $CHAIN_BINARY --home $HOME_1 q ratelimit rate-limit ${{ env.CONSUMERA_CHAN_ID }}
+      - name: _Test rate limit
+        run: |
+          tests/stateful/test_rate_limits.sh
+      - name: _IBC transfer successful> Interchain Security (Consumer) PSS
+        env:
+          CONSUMER_CHAIN_ID: consumera
+        run: |
+          set -e
+          tests/stateful/test_consumer_ibc_transfer.sh ${{ env.CONSUMERA_CHAN_ID }} 2 $WALLET_1 $WALLET_CONSUMER_1 1000
           denom=$(gaiad --home $HOME/.val1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select(.amount=="1000") | .denom')
           echo "consumera denom: $denom"
           echo "CONSUMERA_DENOM=$denom" >> $GITHUB_ENV
-      - name: Send tx on consumer with huge gas (not needed keep commented out)
-        run: |
-          json=$($CONSUMER_CHAIN_BINARY --home $HOME/.cona1 tx bank send consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc consumer1ty2qlurqsxj6sgs378hxmzyxh0ds8ukcm6rgxj 1ucon --gas auto --gas-prices 5000ucon --gas-adjustment 2 -y -o json)
-          echo "[INFO]: Transaction Result..."
-          echo "$json"
-          echo "[INFO]: Wait for 1 block to pass..."
-          tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 1
-          txhash=$(echo "$json" | jq -r .txhash)
-          echo "[INFO]: TX result..."
-          $CONSUMER_CHAIN_BINARY --home $HOME/.cona1 q tx $txhash
+      # - name: Send tx on consumer with huge gas (not needed keep commented out)
+      #   run: |
+      #     json=$($CONSUMER_CHAIN_BINARY --home $HOME/.cona1 tx bank send consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc consumer1ty2qlurqsxj6sgs378hxmzyxh0ds8ukcm6rgxj 1ucon --gas auto --gas-prices 5000ucon --gas-adjustment 2 -y -o json)
+      #     echo "[INFO]: Transaction Result..."
+      #     echo "$json"
+      #     echo "[INFO]: Wait for 1 block to pass..."
+      #     tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 1
+      #     txhash=$(echo "$json" | jq -r .txhash)
+      #     echo "[INFO]: TX result..."
+      #     $CONSUMER_CHAIN_BINARY --home $HOME/.cona1 q tx $txhash
       - name: _Check consumera rewards in rewards pool balances
         run: |
           echo "[INFO]: Wait for 20 blocks to pass"
@@ -654,12 +660,6 @@ jobs:
           sleep 30
           echo "[INFO]: Rewards trigger tx"
           $CONSUMER_CHAIN_BINARY --home $HOME/.cona1 q tx $txhash
-      # - name: DEBUG
-      #   run: |
-      #     while [ ! -f /continue ]
-      #     do
-      #       sleep 1
-      #     done
       - name: _Check validator outstanding rewards for consumer chain a
         run: |
           ls $HOME/artifact
@@ -688,7 +688,6 @@ jobs:
           else
             echo "[PASS] Denom is in validator's outstanding rewards: $denom"
           fi
-
       - name: Initialize consumer chain B with Interchain Security (Consumer) PSS
         env:
           CONSUMER_CHAIN_ID: consumerb
@@ -727,34 +726,34 @@ jobs:
         run: tests/test_block_production.sh 127.0.0.1 $CONB1_RPC_PORT 10
       - name: _TopN consumer chain produces blocks val2> ICS v4.0.0
         run: tests/test_block_production.sh 127.0.0.1 $CONB2_RPC_PORT 10
-      # - name: Check block hashes on both consumerb nodes
-      #   run: |
-      #     set -e
-      #     latest_block=$($CONSUMER_CHAIN_BINARY --home $CONSUMERB_HOME_1 status | jq -r '.SyncInfo.latest_block_height')
-      #     echo "[INFO]: Block height is $latest_block"
-      #     hash_val1=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
-      #     sleep 6
-      #     hash_val2=$(curl -s 127.0.0.1:$CONB2_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
-      #     echo "[INFO]: conb1 $hash_val1"
-      #     echo "[INFO]: conb2 $hash_val2"
-      #     if [ $hash_val1 != $hash_val2 ]
-      #     then
-      #       echo "[ERROR]: Block hash does not match. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
-      #       exit 1
-      #     else
-      #       echo "[INFO]: Block hash matches. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
-      #     fi
-      # - name: Check number of signatures on consumerb
-      #   run: |
-      #     set -e
-      #     total_signatures=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
-      #     if [ $total_signatures != 1 ]
-      #     then
-      #       echo "[ERROR]: Unexpected number of validators $total_signatures, expected 1"
-      #       exit 1
-      #     else
-      #       echo "Expected correct number of validators: $total_signatures"
-      #     fi
+      - name: Check block hashes on both consumerb nodes
+        run: |
+          set -e
+          latest_block=$($CONSUMER_CHAIN_BINARY --home $CONSUMERB_HOME_1 status | jq -r '.sync_info.latest_block_height')
+          echo "[INFO]: Block height is $latest_block"
+          hash_val1=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
+          tests/test_block_production.sh 127.0.0.1 $CONB1_RPC_PORT 1 10
+          hash_val2=$(curl -s 127.0.0.1:$CONB2_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
+          echo "[INFO]: conb1 $hash_val1"
+          echo "[INFO]: conb2 $hash_val2"
+          if [ $hash_val1 != $hash_val2 ]
+          then
+            echo "[ERROR]: Block hash does not match. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
+            exit 1
+          else
+            echo "[INFO]: Block hash matches. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
+          fi
+      - name: Check number of signatures on consumerb
+        run: |
+          set -e
+          total_signatures=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
+          if [ $total_signatures != 1 ]
+          then
+            echo "[ERROR]: Unexpected number of validators $total_signatures, expected 1"
+            exit 1
+          else
+            echo "Expected correct number of validators: $total_signatures"
+          fi
       - name: Establish CCV channel for consumerb
         run: |
           set -e
@@ -988,13 +987,6 @@ jobs:
           export EXPEDITED_PERIOD=$($CHAIN_BINARY --home $HOME_1 q gov params -o json | jq -r '.params.expedited_voting_period')
           echo "EXPEDITED_PERIOD set to: $EXPEDITED_PERIOD"
           tests/stateful/gaia-v18/test_expedited_proposal.sh
-     
-      # - name: DEBUG
-      #   run: |
-      #     while [ ! -f /continue ]
-      #     do
-      #       sleep 1
-      #     done
 
       - name: _TX load tests
         run: tests/test_load_tx.sh --rpc-host 127.0.0.1 --rpc-port $VAL1_RPC_PORT --home $HOME_1 --from-wallet $WALLET_1 --to-wallet $WALLET_2 --valoper_address_1 $VALOPER_1 --liquid-transfer-to cosmos1jf7j9nvjmnflal5ehaj25p7nsk2t3lkd3tj7zp
@@ -1463,7 +1455,13 @@ jobs:
             echo "[ERROR]: No insufficient fee from log!"
             exit 1
           fi
-      # TX tests
+      # - name: DEBUG
+      #   if: always() && !cancelled()
+      #   run: |
+      #     while [ ! -f /continue ]
+      #     do
+      #       sleep 1
+      #     done
       - name: Stop services
         if: always()
         run: |
