move multi-send to end of test

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -253,6 +253,9 @@ jobs:
           echo "[INFO] val2:"
           wallets=$(gaiad --home $HOME_2 keys list --output json | jq -r '.[].address ')
           for i in $wallets; do echo "Balances in wallet $i: "; gaiad --home $HOME_2 q bank balances $i; done
+      - name: Print starting validator set
+        run: |
+          $CHAIN_BINARY --home $HOME_1 q comet-validator-set 
       - name: Query default validator description
         run: |
           set -e
@@ -285,79 +288,6 @@ jobs:
           if [ $error == 1 ]
           then
             exit 1
-          fi
-      - name: _Test bank multi-send to 1 wallet
-        run : |
-          source ~/env/bin/activate
-          # tests/stateful/test_multi-send_gas.sh <1 wallets> <number of tokens to send> <denom> <gas-adjustment> <gas-prices>
-          tests/stateful/test_multi-send_gas.sh 50 1 uatom 2 3000uatom
-      - name: _Test bank multi-send to 5 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 5 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 10 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 10 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 50 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 50 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 100 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 100 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 150 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 150 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 200 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 200 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 250 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 250 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 300 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 300 10 uatom 2 3000uatom
-      - name: _Test bank multi-send to 350 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 350 10 uatom 1.5 3000uatom
-      - name: _Test bank multi-send to 400 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 400 10 uatom 1 3000uatom
-      - name: _Test bank multi-send to 450 wallets
-        run : |
-          source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 450 10 uatom 1 12000uatom
-      - name: _Test bank multi-send to 500 wallets
-        run : |
-          source ~/env/bin/activate
-          set +e
-          tests/stateful/test_multi-send_gas.sh 500 10 uatom 1 80000uatom
-          if [ $? -eq 0 ]
-          then
-              echo "[FAIL]: TX was successful"
-              exit 1
-          else
-            echo "[PASS]: TX was not successful"
-          fi
-      - name: _Test bank multi-send to 501 wallets
-        run : |
-          source ~/env/bin/activate
-          set +e
-          tests/stateful/test_multi-send_gas.sh 501 10 uatom 1 80000uatom
-          if [ $? -eq 0 ]
-          then
-              echo "[FAIL]: TX was successful"
-              exit 1
-          else
-            echo "[PASS]: TX was not successful"
           fi
       - name: Query staking params
         run: |
@@ -744,6 +674,81 @@ jobs:
 
       - name: _TX load tests
         run: tests/test_load_tx.sh --rpc-host 127.0.0.1 --rpc-port $VAL1_RPC_PORT --home $HOME_1 --from-wallet $WALLET_1 --to-wallet $WALLET_2 --valoper_address_1 $VALOPER_1 --liquid-transfer-to cosmos1jf7j9nvjmnflal5ehaj25p7nsk2t3lkd3tj7zp
+      
+      ### Multi-send tests
+      - name: _Test bank multi-send to 1 wallet
+        run : |
+          source ~/env/bin/activate
+          # tests/stateful/test_multi-send_gas.sh <1 wallets> <number of tokens to send> <denom> <gas-adjustment> <gas-prices>
+          tests/stateful/test_multi-send_gas.sh 50 1 uatom 2 3000uatom
+      - name: _Test bank multi-send to 5 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 5 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 10 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 10 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 50 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 50 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 100 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 100 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 150 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 150 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 200 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 200 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 250 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 250 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 300 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 300 10 uatom 2 3000uatom
+      - name: _Test bank multi-send to 350 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 350 10 uatom 1.5 3000uatom
+      - name: _Test bank multi-send to 400 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 400 10 uatom 1 3000uatom
+      - name: _Test bank multi-send to 450 wallets
+        run : |
+          source ~/env/bin/activate
+          tests/stateful/test_multi-send_gas.sh 450 10 uatom 1 12000uatom
+      - name: _Test bank multi-send to 500 wallets
+        run : |
+          source ~/env/bin/activate
+          set +e
+          tests/stateful/test_multi-send_gas.sh 500 10 uatom 1 80000uatom
+          if [ $? -eq 0 ]
+          then
+              echo "[FAIL]: TX was successful"
+              exit 1
+          else
+            echo "[PASS]: TX was not successful"
+          fi
+      - name: _Test bank multi-send to 501 wallets
+        run : |
+          source ~/env/bin/activate
+          set +e
+          tests/stateful/test_multi-send_gas.sh 501 10 uatom 1 80000uatom
+          if [ $? -eq 0 ]
+          then
+              echo "[FAIL]: TX was successful"
+              exit 1
+          else
+            echo "[PASS]: TX was not successful"
+          fi
 
       ### Param tests
       - name: Query current consensus params
