submit ICS proposal

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -532,6 +532,30 @@
                 exit 1
               fi
 
+          - name: Submit ICS proposal
+            run: |
+              source scripts/vars.sh  
+              source scripts/vars_consumer_v640_one.sh
+              echo "> Broadcasting proposal"
+              result=$($CHAIN_BINARY tx broadcast signed-proposal.json --home $whale_home -y -o json)
+              echo "> Broadcast result: $result"
+              txhash=$(echo $result | jq -r '.txhash')
+              raw_log=$(echo $result | jq -r '.raw_log')
+              echo "> Transaction hash: $txhash"
+              echo "> Raw log: $raw_log"
+              sleep $(($COMMIT_TIMEOUT*2))
+              echo "> Querying transaction hash $txhash"
+              # The result of the tx query must result in a "not found" error.
+              query_result=$($CHAIN_BINARY q tx $txhash --home $whale_home -o json 2>&1 || true)
+              echo "> Query result: $query_result"
+              if echo "$query_result" | grep -q "not found"; then
+                echo "> PASS: Transaction not found"
+              else
+                echo "> FAIL: Transaction was found"
+                exit 1
+              fi
+
+
           - name: Restart chain
             run: |
               source scripts/vars.sh
