remove ccv check after upgrade

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -825,11 +825,11 @@
               sleep $(($COMMIT_TIMEOUT*2))
               scripts/start_relayer.sh
 
-          - name: _CCV channel verified> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh  
-              tests/test_ccv_channel.sh
+          # - name: _CCV channel verified> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh  
+          #     tests/test_ccv_channel.sh
 
           - name: _IBC transfer successful> ICS v6.4.0 chain 1
             run: |
@@ -840,43 +840,43 @@
               channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
               tests/test_consumer_ibc_transfer.sh $channel_id channel-1
           
-          - name: _Downtime test> ICS v6.4.0
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh
-              tests/test_consumer_downtime.sh
+          # - name: _Downtime test> ICS v6.4.0
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh
+          #     tests/test_consumer_downtime.sh
             
-          - name: _Test consumer equivocation
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh
-              tests/test_consumer_equivocation.sh
-          - name: _Test consumer light client attack
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh
-              source scripts/vars_consumer_v400_lc.sh
-              tests/test_consumer_light_client_legacy.sh
+          # - name: _Test consumer equivocation
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh
+          #     tests/test_consumer_equivocation.sh
+          # - name: _Test consumer light client attack
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh
+          #     source scripts/vars_consumer_v400_lc.sh
+          #     tests/test_consumer_light_client_legacy.sh
 
-          - name: _Remove consumer chain> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh
-              echo "Consumer chains:"
-              $CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq '.'
-              consumer_id=$($CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).consumer_id')
-              echo "Removing v640-one (consumer_id = $consumer_id):"
-              txhash=$($CHAIN_BINARY tx provider remove-consumer $consumer_id --from $WALLET_1 --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home -o json | jq -r '.txhash')
-              sleep $(($COMMIT_TIMEOUT*2))
-              $CHAIN_BINARY q tx $txhash -o json --home $whale_home | jq '.'
-              $CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq '.'
-              phase=$($CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id == $chain).phase')
-              if [[ "$phase" -eq "CONSUMER_PHASE_STOPPED" ]]; then
-                echo "PASS: Consumer chain was stopped."
-              else
-                echo "FAIL: Consumer chain was not stopped."
-                exit 1
-              fi
+          # - name: _Remove consumer chain> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh
+          #     echo "Consumer chains:"
+          #     $CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq '.'
+          #     consumer_id=$($CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).consumer_id')
+          #     echo "Removing v640-one (consumer_id = $consumer_id):"
+          #     txhash=$($CHAIN_BINARY tx provider remove-consumer $consumer_id --from $WALLET_1 --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home -o json | jq -r '.txhash')
+          #     sleep $(($COMMIT_TIMEOUT*2))
+          #     $CHAIN_BINARY q tx $txhash -o json --home $whale_home | jq '.'
+          #     $CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq '.'
+          #     phase=$($CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id == $chain).phase')
+          #     if [[ "$phase" -eq "CONSUMER_PHASE_STOPPED" ]]; then
+          #       echo "PASS: Consumer chain was stopped."
+          #     else
+          #       echo "FAIL: Consumer chain was not stopped."
+          #       exit 1
+          #     fi
 
       Test-03-ics-topn:
         runs-on: ubuntu-24.04
