move test

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -266,21 +266,7 @@ jobs:
           UPGRADE_HEIGHT=$($CHAIN_BINARY --home $HOME_1 q upgrade applied v28.0.0 -o json  | jq -r '.height')
           echo "Upgrade height: $UPGRADE_HEIGHT"
           echo "UPGRADE_HEIGHT=$UPGRADE_HEIGHT" >> $GITHUB_ENV
-          
-      - name: _Validator set checks
-        run: |
-          source ~/env/bin/activate
-          python scripts/ics_removal_validator_check.py --height ${{ env.UPGRADE_HEIGHT }} --binary $CHAIN_BINARY --api http://localhost:$VAL1_API_PORT --rpc http://localhost:$VAL1_RPC_PORT --provider-max-vals ${{ env.PROVIDER_VALIDATORS }} --ics-removal-upgrade
-          check_result=$(jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | grep FAIL || true)
-          echo "Check result: $check_result"
-          if [ -z "$check_result" ]; then
-            echo "> PASS: Validator set check passed"
-          else
-            echo "> FAIL: Validator set check failed"
-            jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
-            exit 0
-          fi
-
+      
       - name: Stop services
         if: always()
         run: |
@@ -349,6 +335,20 @@ jobs:
           do
             sleep 1
           done
+          
+      - name: _Validator set checks
+        run: |
+          source ~/env/bin/activate
+          python scripts/ics_removal_validator_check.py --height ${{ env.UPGRADE_HEIGHT }} --binary $CHAIN_BINARY --api http://localhost:$VAL1_API_PORT --rpc http://localhost:$VAL1_RPC_PORT --provider-max-vals ${{ env.PROVIDER_VALIDATORS }} --ics-removal-upgrade
+          check_result=$(jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | grep FAIL || true)
+          echo "Check result: $check_result"
+          if [ -z "$check_result" ]; then
+            echo "> PASS: Validator set check passed"
+          else
+            echo "> FAIL: Validator set check failed"
+            jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
+            exit 0
+          fi
 
       - name: _Consumer rewards balances check
         run: |
