try opt in second val conb

diff --git a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
@@ -658,16 +658,6 @@ jobs:
           else
             echo "[INFO]: Block hash matches. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
           fi
-      # - name: Print opt-in consumer tendermint validators
-      #   env:
-      #     CONSUMER_CHAIN_ID: consumerb
-      #   run: |
-      #     echo "[INFO]: $CONSUMER_CHAIN_BINARY q tendermint-validator-set"
-      #     $CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 q tendermint-validator-set -o json | jq -r '.'
-      #     # echo "[INFO]: $CHAIN_BINARY q provider has-to-validate"
-      #     # $CHAIN_BINARY --home $HOME_1 q provider has-to-validate -o json | jq -r '.'
-      #     echo "[INFO]: $CHAIN_BINARY q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID"
-      #     $CHAIN_BINARY --home $HOME_1 q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID -o json | jq -r '.'
       - name: Check number of signatures on consumerb
         run: |
           total_signatures=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
@@ -720,6 +710,31 @@ jobs:
           echo "Channel ID: $channel_id"
           tests/stateful/test_consumer_ibc_transfer.sh $channel_id 2 $WALLET_1 $WALLET_CONSUMER_1
           echo "CONSUMERA_CHAN_ID=$channel_id" >> $GITHUB_ENV
+      - name: Print opt-in consumer tendermint validators
+        env:
+          CONSUMER_CHAIN_ID: consumerb
+        run: |
+          echo "[INFO]: $CONSUMER_CHAIN_BINARY q tendermint-validator-set"
+          $CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 q tendermint-validator-set -o json | jq -r '.'
+          # echo "[INFO]: $CHAIN_BINARY q provider has-to-validate"
+          # $CHAIN_BINARY --home $HOME_1 q provider has-to-validate -o json | jq -r '.'
+          echo "[INFO]: $CHAIN_BINARY q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID"
+          $CHAIN_BINARY --home $HOME_1 q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID -o json | jq -r '.'
+      - name: Opt-in second validator to consumerb chain
+        run: |
+          echo "[INFO] Optin second validator"
+          node_key2=$($CONSUMER_CHAIN_BINARY --home $CONSUMERB_HOME_2 tendermint show-validator)
+          $CHAIN_BINARY --home $HOME_2 tx provider opt-in ${{ env.CONSUMER_ID_TOPN }} "$node_key2" --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --from val2 -y
+      - name: Check number of signatures on consumerb
+        run: |
+          total_signatures=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
+          if [ $total_signatures != 2 ]
+          then
+            echo "[ERROR]: Unexpected number of validators $total_signatures, expected 2"
+            exit 1
+          else
+            echo "Expected correct number of validators: $total_signatures"
+          fi
       # - name: Set BlocksPerEpoch to 100
       #   run: scripts/submit_proposal.sh templates/proposal-blocks-per-epoch-100.json
       # - name: Check BlocksPerEpoch is 100
