validator set checks

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -415,6 +415,68 @@
               source scripts/vars.sh
               tests/test_block_production.sh 127.0.0.1 ${rpc_prefix}$COUNT_WIDTH 5
 
+          - name: Validator set checks
+            run: |
+              source scripts/vars.sh
+              export validator_count=10
+              export MAX_VALIDATORS=8
+              export MAX_PROVIDER_VALIDATORS=5
+              python scripts/ics_removal_validator_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --provider-max-vals $MAX_PROVIDER_VALIDATORS --ics-removal-upgrade
+              jq '.' validator-check-$UPGRADE_HEIGHT.json
+              check_result=$(jq -r '.' validator-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
+              echo "Check result: $check_result"
+              if [ -z "$check_result" ]; then
+                echo "> PASS: Validator set check passed"
+              else
+                echo "> FAIL: Validator set check failed"
+                jq '.' validator-check-$UPGRADE_HEIGHT.json
+                exit 1
+              fi
+              echo "> Verify that operations occurred at upgrade height"
+              operations=$(jq -r '.operations' validator-check-$UPGRADE_HEIGHT.json)
+              echo "> Operations: $operations"
+              if [ "${{ matrix.operation }}" != "no-rotation" ]; then
+                # Verify that operations array is not empty
+                if [ "$operations" != "[]" ]; then
+                  echo "> PASS: Operations occurred at upgrade height as expected for operation ${{ matrix.operation }}"
+                else
+                  echo "> FAIL: No operations occurred at upgrade height for operation ${{ matrix.operation }}"
+                  exit 1
+                fi
+              fi
+
+          - name: Consumer rewards balances check
+            run: |
+              source scripts/vars.sh
+              $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
+              $CHAIN_BINARY q distribution community-pool --home $whale_home -o json | jq '.'
+              python scripts/ics_removal_consumer_rewards_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --ics-removal-upgrade
+              jq '.' rewards-check-$UPGRADE_HEIGHT.json
+              check_result=$(jq -r '.' rewards-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
+              echo "Check result: $check_result"
+              if [ -z "$check_result" ]; then
+                echo "> PASS: Consumer rewards balances check passed"
+              else
+                echo "> FAIL: Consumer rewards balances check failed"
+                jq '.' rewards-check-$UPGRADE_HEIGHT.json
+                exit 1
+              fi    
+
+          - name: IBC channels check
+            run: |
+              source scripts/vars.sh  
+              python scripts/ics_removal_ibc_channels_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --ics-removal-upgrade
+              jq '.' channels-check-$UPGRADE_HEIGHT.json
+              check_result=$(jq -r '.' channels-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
+              echo "Check result: $check_result"
+              if [ -z "$check_result" ]; then
+                echo "> PASS: IBC channels check passed"
+              else
+                echo "> FAIL: IBC channels check failed"
+                jq '.' channels-check-$UPGRADE_HEIGHT.json
+                exit 1
+              fi    
+
           - name: Restart chain
             run: |
               source scripts/vars.sh
@@ -492,68 +554,6 @@
           #     source scripts/vars.sh
           #     $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
           #     $CHAIN_BINARY q distribution community-pool --home $whale_home -o json | jq '.'
-
-          # - name: Validator set checks
-          #   run: |
-          #     source scripts/vars.sh
-          #     export validator_count=10
-          #     export MAX_VALIDATORS=8
-          #     export MAX_PROVIDER_VALIDATORS=5
-          #     python scripts/ics_removal_validator_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --provider-max-vals $MAX_PROVIDER_VALIDATORS --ics-removal-upgrade
-          #     jq '.' validator-check-$UPGRADE_HEIGHT.json
-          #     check_result=$(jq -r '.' validator-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
-          #     echo "Check result: $check_result"
-          #     if [ -z "$check_result" ]; then
-          #       echo "> PASS: Validator set check passed"
-          #     else
-          #       echo "> FAIL: Validator set check failed"
-          #       jq '.' validator-check-$UPGRADE_HEIGHT.json
-          #       exit 1
-          #     fi
-          #     echo "> Verify that operations occurred at upgrade height"
-          #     operations=$(jq -r '.operations' validator-check-$UPGRADE_HEIGHT.json)
-          #     echo "> Operations: $operations"
-          #     if [ "${{ matrix.operation }}" != "no-rotation" ]; then
-          #       # Verify that operations array is not empty
-          #       if [ "$operations" != "[]" ]; then
-          #         echo "> PASS: Operations occurred at upgrade height as expected for operation ${{ matrix.operation }}"
-          #       else
-          #         echo "> FAIL: No operations occurred at upgrade height for operation ${{ matrix.operation }}"
-          #         exit 1
-          #       fi
-          #     fi
-
-          # - name: Consumer rewards balances check
-          #   run: |
-          #     source scripts/vars.sh
-          #     $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
-          #     $CHAIN_BINARY q distribution community-pool --home $whale_home -o json | jq '.'
-          #     python scripts/ics_removal_consumer_rewards_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --ics-removal-upgrade
-          #     jq '.' rewards-check-$UPGRADE_HEIGHT.json
-          #     check_result=$(jq -r '.' rewards-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
-          #     echo "Check result: $check_result"
-          #     if [ -z "$check_result" ]; then
-          #       echo "> PASS: Consumer rewards balances check passed"
-          #     else
-          #       echo "> FAIL: Consumer rewards balances check failed"
-          #       jq '.' rewards-check-$UPGRADE_HEIGHT.json
-          #       exit 1
-          #     fi    
-
-          # - name: IBC channels check
-          #   run: |
-          #     source scripts/vars.sh  
-          #     python scripts/ics_removal_ibc_channels_check.py --height $UPGRADE_HEIGHT --binary $CHAIN_BINARY --api http://localhost:$whale_api --rpc http://localhost:$whale_rpc --ics-removal-upgrade
-          #     jq '.' channels-check-$UPGRADE_HEIGHT.json
-          #     check_result=$(jq -r '.' channels-check-$UPGRADE_HEIGHT.json | grep FAIL || true)
-          #     echo "Check result: $check_result"
-          #     if [ -z "$check_result" ]; then
-          #       echo "> PASS: IBC channels check passed"
-          #     else
-          #       echo "> FAIL: IBC channels check failed"
-          #       jq '.' channels-check-$UPGRADE_HEIGHT.json
-          #       exit 1
-          #     fi    
 
           # - name: Check for open provider channels after upgrade
           #   run: |
