Fix/stateful liquid (#165)

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -1106,6 +1106,10 @@ jobs:
         run: |
           echo "Query current staking params"
           $CHAIN_BINARY --home $HOME_1 q staking params -o json | jq -r '.'
+      - name: Query current liquid params
+        run: |
+          echo "Query current liquid params"
+          $CHAIN_BINARY --home $HOME_1 q liquid params -o json | jq -r '.'
       - name: Query current gov params
         run: |
           echo "Query current gov params"
@@ -1357,6 +1361,31 @@ jobs:
           if [ "$Q_MIN_COMMISSION_RATE" != "$MIN_COMMISSION_RATE" ]
           then
             echo "[ERROR]: MIN_COMMISSION_RATE does not match query: $MIN_COMMISSION_RATE $Q_MIN_COMMISSION_RATE"
+            error="1"
+          fi
+          if [ "$error" == "1" ]
+          then
+            exit 1
+          else
+            echo "PASSED!"
+          fi
+      - name: _Verify liquid params prop is set
+        env:
+          GLOBAL_LIQUID_STAKING_CAP: "0.200000000000000000"
+          VALIDATOR_LIQUID_STAKING_CAP: "0.400000000000000000"
+        run: |
+          echo "[INFO]: Current params:"
+          $CHAIN_BINARY --home $HOME_1 q liquid params -o json | jq -r '.'
+          Q_GLOBAL_LIQUID_STAKING_CAP=$($CHAIN_BINARY --home $HOME_1 q liquid params -o json | jq -r '.params.global_liquid_staking_cap')
+          Q_VALIDATOR_LIQUID_STAKING_CAP=$($CHAIN_BINARY --home $HOME_1 q liquid params -o json | jq -r '.params.validator_liquid_staking_cap')
+          if [ "$Q_GLOBAL_LIQUID_STAKING_CAP" != "$GLOBAL_LIQUID_STAKING_CAP" ]
+          then
+            echo "[ERROR]: GLOBAL_LIQUID_STAKING_CAP does not match query: $GLOBAL_LIQUID_STAKING_CAP $Q_GLOBAL_LIQUID_STAKING_CAP"
+            error="1"
+          fi
+          if [ "$Q_VALIDATOR_LIQUID_STAKING_CAP" != "$VALIDATOR_LIQUID_STAKING_CAP" ]
+          then
+            echo "[ERROR]: VALIDATOR_LIQUID_STAKING_CAP does not match query: $VALIDATOR_LIQUID_STAKING_CAP $Q_VALIDATOR_LIQUID_STAKING_CAP"
             error="1"
           fi
           if [ "$error" == "1" ]
