add consumer rewards check

diff --git a/.github/workflows/upgrade-gaia-v28-verification.yml b/.github/workflows/upgrade-gaia-v28-verification.yml
--- a/.github/workflows/upgrade-gaia-v28-verification.yml
+++ b/.github/workflows/upgrade-gaia-v28-verification.yml
@@ -87,3 +87,18 @@ jobs:
             jq -r '.' channels-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
             exit 1
           fi
+      - name: Consumer rewards check
+        run: |
+          set -e
+          source ~/env/bin/activate
+          python scripts/ics_removal_ibc_consumer_rewards.py --height ${{ env.UPGRADE_HEIGHT }} --binary gaiad --api ${{ env.API }} --rpc ${{ env.RPC }} --ics-removal-upgrade
+          check_result=$(jq -r '.' rewards-check-${{ env.UPGRADE_HEIGHT }}.json | grep FAIL || true)
+          echo "Check result: $check_result"
+          if [ -z "$check_result" ]; then
+            echo "> PASS: Consumer rewards balances check passed"
+          else
+            echo "> FAIL: Consumer rewards balances check failed"
+            jq '.' rewards-check-${{ env.UPGRADE_HEIGHT }}.json
+            jq -r '.' rewards-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
+            exit 1
+          fi
