pre-gov params test

diff --git a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
@@ -462,6 +462,76 @@ jobs:
 
 
       ### Param tests
+      - name: _Pre-proposal Verify Gov params
+        run: |
+          echo "Verify deposit is not burned when quorum is reached by voting no"
+          starting_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Starting balance: $starting_balance"
+          echo "[INFO]: Submiting proposal and voting no"
+          scripts/submit_proposal.sh templates/proposal-text.json no
+          current_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Balance after no vote: $current_balance"
+          echo "[INFO]: Calculate currect balance"
+          expected_balance=$(echo "$starting_balance - $BASE_FEES - $BASE_FEES" | bc)
+          echo "[DEBUG]: expected_balance: $expected_balance"
+          if [ $expected_balance -ne $current_balance ]
+          then
+            echo "[ERROR] Amount is not correct"
+            echo "Expected balance should be $expected_balance, bank have $current_balance"
+            error="1"
+          else
+            echo "Bank balance matches the caluclated balance"
+            echo "Expected balance is $expected_balance and bank have $current_balance"
+          fi
+
+          echo "[INFO]: Verify deposit is burned when no_with_veto passed"
+          starting_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Starting balance: $starting_balance"
+          echo "[INFO]: Submiting proposal and voting no"
+          scripts/submit_proposal.sh templates/proposal-text.json no_with_veto
+          current_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Balance after no vote: $current_balance"
+          echo "[INFO]: Calculate currect balance"
+          expected_balance=$(echo "$starting_balance - $BASE_FEES - $BASE_FEES - 100000000" | bc)
+          echo "[DEBUG]: expected_balance: $expected_balance"
+          if [ $expected_balance -ne $current_balance ]
+          then
+            echo "[ERROR] Amount is not correct"
+            echo "Expected balance should be $expected_balance, bank have $current_balance"
+            error="1"
+          else
+            echo "Bank balance matches the caluclated balance"
+            echo "Expected balance is $expected_balance and bank have $current_balance"
+          fi
+
+          echo "[INFO]: Verify deposit is not burned when quorum is not reached"
+          starting_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Starting balance: $starting_balance"
+          echo "[INFO]: Submiting proposal and voting no"
+          $CHAIN_BINARY tx gov submit-proposal templates/proposal-text.json --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --from $WALLET_1 --keyring-backend test --home $HOME_1 --chain-id $CHAIN_ID -b sync -y -o json
+          echo "[INFO]: Wait for voting period to end..."
+          sleep $VOTING_PERIOD
+          current_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
+          echo "[INFO]: Balance after no vote: $current_balance"
+          echo "[INFO]: Calculate currect balance"
+          expected_balance=$(echo "$starting_balance - $BASE_FEES" | bc)
+          echo "[DEBUG]: expected_balance: $expected_balance"
+          if [ $expected_balance -ne $current_balance ]
+          then
+            echo "[ERROR] Amount is not correct"
+            echo "Expected balance should be $expected_balance, bank have $current_balance"
+            error="1"
+          else
+            echo "Bank balance matches the caluclated balance"
+            echo "Expected balance is $expected_balance and bank have $current_balance"
+          fi
+
+          if [ "$error" == "1" ]
+          then
+            exit 1
+          else
+            echo "PASSED!"
+          fi
       - name: Query current consensus params
         run: |
           echo "Query current consensus params"
@@ -765,7 +835,7 @@ jobs:
           fi
       - name: _Verify Gov params
         run: |
-          echo "Verify deposit not burned when quorum is reached voting no"
+          echo "Verify deposit is not burned when quorum is reached by voting no"
           starting_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
           echo "[INFO]: Starting balance: $starting_balance"
           echo "[INFO]: Submiting proposal and voting no"
