add tests

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -5600,11 +5600,11 @@
           #     tests/test_bank.sh
 
 
-          # - name: _Test validator jailing and slashing
-          #   run: |
-          #     source scripts/vars.sh
-          #     export validator_count=12
-          #     tests/test_downtime.sh
+          - name: _Test validator jailing and slashing
+            run: |
+              source scripts/vars.sh
+              export validator_count=12
+              tests/test_downtime.sh
 
           # - name: Restart relayer
           #   run: |
@@ -5621,42 +5621,42 @@
           #     source scripts/vars.sh
           #     tests/test_liquid_happy_path.sh
 
-          # - name: Tokenize with upgrade_wallet
-          #   run: |
-          #     source scripts/vars.sh
-          #     upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
-          #     echo "> Delegating."
-          #     $CHAIN_BINARY tx staking delegate $VALOPER_1 1000000uatom --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
-          #     sleep $(($COMMIT_TIMEOUT+2))
-          #     echo "> Tokenizing."
-          #     echo "> Command: $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
-          #     $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
-          #     sleep $(($COMMIT_TIMEOUT+2))
-          #     $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
+          - name: Tokenize with upgrade_wallet
+            run: |
+              source scripts/vars.sh
+              upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
+              echo "> Delegating."
+              $CHAIN_BINARY tx staking delegate $VALOPER_1 1000000uatom --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
+              sleep $(($COMMIT_TIMEOUT+2))
+              echo "> Tokenizing."
+              echo "> Command: $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
+              $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
+              sleep $(($COMMIT_TIMEOUT+2))
+              $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
           
-          # - name: Redeem tokens with upgrade_wallet
-          #   run: |
-          #     source scripts/vars.sh
-          #     upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
-          #     $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     liquid_denom=$($CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq -r --arg valoper "$VALOPER_1" '.balances | map(select(.denom | startswith($valoper))) | .[-1].denom')
-          #     $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     starting_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
-          #     echo "> Denom: $liquid_denom"
-          #     echo "> Command: $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $whale_home -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
-          #     $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
-          #     sleep $(($COMMIT_TIMEOUT+2))
-          #     $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     ending_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
-          #     diff=$(echo "$ending_delegation_amount - $starting_delegation_amount" | bc)
-          #     echo "> Difference in delegation amount: $diff"
-          #     if [[ "$diff" == "1000000" ]]; then
-          #         echo "Token redemption succeeded."
-          #     else
-          #         echo "Token redemption failed."
-          #         exit 1
-          #     fi
+          - name: Redeem tokens with upgrade_wallet
+            run: |
+              source scripts/vars.sh
+              upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
+              $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
+              liquid_denom=$($CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq -r --arg valoper "$VALOPER_1" '.balances | map(select(.denom | startswith($valoper))) | .[-1].denom')
+              $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
+              starting_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
+              echo "> Denom: $liquid_denom"
+              echo "> Command: $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $whale_home -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
+              $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
+              sleep $(($COMMIT_TIMEOUT+2))
+              $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
+              $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
+              ending_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
+              diff=$(echo "$ending_delegation_amount - $starting_delegation_amount" | bc)
+              echo "> Difference in delegation amount: $diff"
+              if [[ "$diff" == "1000000" ]]; then
+                  echo "Token redemption succeeded."
+              else
+                  echo "Token redemption failed."
+                  exit 1
+              fi
     
           # - name: _Test ICA send
           #   run: |
@@ -5666,29 +5666,29 @@
           #     recipient_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="recipient2").address')
           #     tests/test_ica_send.sh $controller1 $recipient_wallet
 
-          # - name: _Test counter contract
-          #   run: |
-          #     source scripts/vars.sh
-          #     tests/test_contract_counter.sh
+          - name: _Test counter contract
+            run: |
+              source scripts/vars.sh
+              tests/test_contract_counter.sh
 
-          # - name: _Test multisig contract
-          #   run: |
-          #     source scripts/vars.sh
-          #     tests/test_contract_multisig.sh
+          - name: _Test multisig contract
+            run: |
+              source scripts/vars.sh
+              tests/test_contract_multisig.sh
 
-          # - name: Create and mint factory denom
-          #   run: |
-          #     source scripts/vars.sh
-          #     scripts/factory_create_mint_denom.sh
+          - name: Create and mint factory denom
+            run: |
+              source scripts/vars.sh
+              scripts/factory_create_mint_denom.sh
           
-          # - name: Test factory denom transfer with PFM
-          #   run: |
-          #     tests/test_factory_pfm_transfer.sh
+          - name: Test factory denom transfer with PFM
+            run: |
+              tests/test_factory_pfm_transfer.sh
 
-          # - name: Test multi-send gas consumption is within expected range
-          #   run: |
-          #     source scripts/vars.sh
-          #     tests/test_multisend_gas_consumption.sh surcharge
+          - name: Test multi-send gas consumption is within expected range
+            run: |
+              source scripts/vars.sh
+              tests/test_multisend_gas_consumption.sh surcharge
 
           - name: Set staking params to bump max validators to 200
             run: |
@@ -5696,8 +5696,6 @@
               export validator_count=12
               echo "> Before:"
               $CHAIN_BINARY q staking params --home $whale_home -o json | jq '.'
-              # jq '.messages[0].params.min_commission_rate="0.000000000000000000"' templates/proposal-staking-params.json > staking-params.json
-              # scripts/param_change.sh staking-params.json
               scripts/param_change.sh templates/proposal-staking-params.json
               echo "> After:"
               $CHAIN_BINARY q staking params --home $whale_home -o json | jq '.'
