try opt out conb

diff --git a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
@@ -738,8 +738,8 @@ jobs:
           echo "$json" | jq -r '.'
           tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
           $CHAIN_BINARY --home $HOME_1 q tx --type=hash $txhash
-      - name: Wait for 20 blocks
-        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 20 600
+      - name: Wait for 1 block
+        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
       - name: Print opt-in consumer tendermint validators consumerb after opt-in
         env:
           CONSUMER_CHAIN_ID: consumerb
@@ -759,6 +759,40 @@ jobs:
           if [ $total_signatures != 2 ]
           then
             echo "[ERROR]: Unexpected number of validators $total_signatures, expected 2"
+            exit 1
+          else
+            echo "Expected correct number of validators: $total_signatures"
+          fi
+      # Opt-out
+      - name: Opt-out second validator to consumerb
+        run: |
+          echo "[INFO] Opt-out second validator"
+          json=$($CHAIN_BINARY --home $HOME_2 tx provider opt-out ${{ env.CONSUMER_ID_TOPN }} --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --from val2 -y -o json)
+          txhash=$(echo "$json" | jq -r .txhash)
+          echo "$json" | jq -r '.'
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
+          $CHAIN_BINARY --home $HOME_1 q tx --type=hash $txhash
+      - name: Wait for 1 block
+        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
+      - name: Print opt-in consumer tendermint validators consumerb after opt-out
+        env:
+          CONSUMER_CHAIN_ID: consumerb
+          CONSUMER_CHAIN_BINARY: ${{ env.CONSUMER_CHAIN_BINARY_2 }}
+          CONSUMER_HOME_1: ${{ env.CONSUMERB_HOME_1 }}
+          CONSUMER_HOME_2: ${{ env.CONSUMERB_HOME_2 }}
+        run: |
+          echo "[INFO]: $CONSUMER_CHAIN_BINARY q tendermint-validator-set"
+          $CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 q tendermint-validator-set -o json | jq -r '.'
+          # echo "[INFO]: $CHAIN_BINARY q provider has-to-validate"
+          # $CHAIN_BINARY --home $HOME_1 q provider has-to-validate -o json | jq -r '.'
+          echo "[INFO]: $CHAIN_BINARY q provider consumer-opted-in-validators ${{ env.CONSUMER_ID_TOPN }}"
+          $CHAIN_BINARY --home $HOME_1 q provider consumer-opted-in-validators ${{ env.CONSUMER_ID_TOPN }} -o json | jq -r '.'
+      - name: _Check number of signatures on consumerb after opt-out
+        run: |
+          total_signatures=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
+          if [ $total_signatures != 1 ]
+          then
+            echo "[ERROR]: Unexpected number of validators $total_signatures, expected 1"
             exit 1
           else
             echo "Expected correct number of validators: $total_signatures"
