add channel and rewards check

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -267,19 +267,49 @@ jobs:
           # echo "UPGRADE_HEIGHT=$UPGRADE_HEIGHT" >> $GITHUB_ENV
           echo "UPGRADE_HEIGHT=30159789" >> $GITHUB_ENV
           
-      # - name: _Validator set checks
-      #   run: |
-      #     source ~/env/bin/activate
-      #     python scripts/validator_check.py --height ${{ env.UPGRADE_HEIGHT }} --binary $CHAIN_BINARY --api http://localhost:$VAL1_API_PORT --rpc http://localhost:$VAL1_RPC_PORT --provider-max-vals ${{ env.PROVIDER_VALIDATORS }} --ics-removal-upgrade
-      #     check_result=$(jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | grep FAIL || true)
-      #     echo "Check result: $check_result"
-      #     if [ -z "$check_result" ]; then
-      #       echo "> PASS: Validator set check passed"
-      #     else
-      #       echo "> FAIL: Validator set check failed"
-      #       jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
-      #       exit 1
-      #     fi
+      - name: _Validator set checks
+        run: |
+          source ~/env/bin/activate
+          python scripts/validator_check.py --height ${{ env.UPGRADE_HEIGHT }} --binary $CHAIN_BINARY --api http://localhost:$VAL1_API_PORT --rpc http://localhost:$VAL1_RPC_PORT --provider-max-vals ${{ env.PROVIDER_VALIDATORS }} --ics-removal-upgrade
+          check_result=$(jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | grep FAIL || true)
+          echo "Check result: $check_result"
+          if [ -z "$check_result" ]; then
+            echo "> PASS: Validator set check passed"
+          else
+            echo "> FAIL: Validator set check failed"
+            jq -r '.' validator-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
+            exit 0
+          fi
+      - name: _Consumer rewards balances check
+        run: |
+          echo "[INFO]: $WALLET_1 balances:"
+          $CHAIN_BINARY q bank balances $WALLET_1 --home $HOME_1 -o json | jq '.'
+          echo "[INFO] community pool distribution:"
+          $CHAIN_BINARY q distribution community-pool --home $HOME_1 -o json | jq '.'
+          python scripts/ics_removal_consumer_rewards_check.py --height ${{ env.UPGRADE_HEIGHT }} --binary $CHAIN_BINARY --api http://localhost:$VAL1_API_PORT --rpc http://localhost:$$VAL1_RPC_PORT --ics-removal-upgrade
+          jq '.' rewards-check-${{ env.UPGRADE_HEIGHT }}.json
+          check_result=$(jq -r '.' rewards-check-${{ env.UPGRADE_HEIGHT }}.json | grep FAIL || true)
+          echo "Check result: $check_result"
+          if [ -z "$check_result" ]; then
+            echo "> PASS: Consumer rewards balances check passed"
+          else
+            echo "> FAIL: Consumer rewards balances check failed"
+            jq '.' rewards-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
+            exit 0
+          fi
+      - name: _IBC channels check
+        run: |
+          python scripts/ics_removal_ibc_channels_check.py --height ${{ env.UPGRADE_HEIGHT }} --binary $CHAIN_BINARY --api http://localhost:$VAL1_API_PORT --rpc http://localhost:$VAL1_RPC_PORT --ics-removal-upgrade
+          jq '.' channels-check-${{ env.UPGRADE_HEIGHT }}.json
+          check_result=$(jq -r '.' channels-check-${{ env.UPGRADE_HEIGHT }}.json | grep FAIL || true)
+          echo "Check result: $check_result"
+          if [ -z "$check_result" ]; then
+            echo "> PASS: IBC channels check passed"
+          else
+            echo "> FAIL: IBC channels check failed"
+            jq '.' channels-check-${{ env.UPGRADE_HEIGHT }}.json | curl -s -H "x-uuid;" --upload-file - 'https://paste.c-net.org/'
+            exit 0
+          fi
       - name: Query default validator description
         run: |
           set -e
@@ -292,6 +322,7 @@ jobs:
           set -e
           $CHAIN_BINARY --home $HOME_1 tx staking edit-validator --new-moniker "Hypha Test Validator" --website "https://hypha.coop" --from val --gas auto --gas-adjustment 3 --gas-prices 1000uatom -y
           tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
+
       - name: _Verify validator description is set
         run: |
           moniker=$($CHAIN_BINARY --home $HOME_1 q staking validator $VALOPER_1 -o json | jq -r '.validator.description.moniker')
@@ -415,6 +446,63 @@ jobs:
             echo "[ERROR]: Unexpected number of validators $total_signatures, expected 2"
             exit 1
           fi
+      
+
+      # - name: Stop services
+      #   if: always()
+      #   run: |
+      #     # hermes
+      #     screen -XS hermes.service quit || true
+      #     killall hermes || true
+      #     sleep 1
+      #     # provider
+      #     killall ${{ env.CHAIN_BINARY }}  || true
+      #     screen -XS {{ env.PROVIDER_SERVICE_1 }} quit || true
+      #     screen -XS {{ env.PROVIDER_SERVICE_2 }} quit || true
+      #     # consumer chains
+      #     killall ${{ env.CONSUMER_CHAIN_BINARY }} || true
+      #     killall ${{ env.CONSUMER_CHAIN_BINARY_2 }} || true
+      #     screen -XS ${{ env.CONSUMER_SERVICE_1 }} quit || true
+      #     screen -XS conb1.service quit || true
+      #     # stride
+      #     killall ${{ env.STRIDE_CHAIN_BINARY }}  || true
+      #     screen -XS ${{ env.STRIDE_SERVICE_1 }} quit || true
+      #     killall screen || true
+      #     sleep 20
+      # # - name: Build fork tool
+      # #   run: |
+      # #     cd /home/runner
+      # #     git clone https://github.com/cosmos/gaia.git
+      # #     cd gaia
+      # #     # git checkout ${{ env.RUNNING_VERSION }}
+      # #     git checkout ${{ vars.FORK_TOOL_TAG }}
+      # #     make build BUILD_TAGS="-tag unsafe_start_local_validator"
+      # #     cp build/gaiad $HOME/go/bin/gaiad-fork
+      # - name: Download fork tool
+      #   run: |
+      #     wget -O $HOME/go/bin/gaiad-fork https://github.com/hyphacoop/cosmos-builds/releases/download/v27.0.0-fork/gaiad
+      #     chmod +x $HOME/go/bin/go/bin/gaiad-fork
+
+      # - name: Make snapshot of val1
+      #   run: |
+      #     cp -rvp $HOME_1 $HOME/.gaia
+      # - name: _Test fork tool
+      #   run: |
+      #     screen -L -Logfile $HOME/artifact/gaiad_fork.log -S $CHAIN_BINARY -d -m /home/runner/go/bin/gaiad-fork --home $HOME/.gaia testnet unsafe-start-local-validator \
+      #     --validator-operator cosmosvaloper1r5v5srda7xfth3hn2s26txvrcrntldju7lnwmv \
+      #     --validator-pubkey "$pubkey" \
+      #     --validator-privkey "$privkey" \
+      #     --accounts-to-fund cosmos1r5v5srda7xfth3hn2s26txvrcrntldjumt8mhl \
+      #     --auto-find-target
+      # - name: DEBUG
+      #   if: always() && !cancelled()
+      #   run: |
+      #     while [ ! -f /continue ]
+      #     do
+      #       sleep 1
+      #     done
+
+
       - name: _Test disabled command provider create-consumer
         env:
           CONSUMER_CHAIN_ID: consumera
@@ -423,13 +511,6 @@ jobs:
           CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
         run: tests/stateful/test_removed_ics.sh
 
-      # - name: DEBUG
-      #   if: always() && !cancelled()
-      #   run: |
-      #     while [ ! -f /continue ]
-      #     do
-      #       sleep 1
-      #     done
       - name: _Test Tokenfactory
         run: tests/stateful/test_tokenfactory.sh
       - name: _Test vesting accounts
@@ -1248,6 +1329,7 @@ jobs:
           # provider
           killall ${{ env.CHAIN_BINARY }}  || true
           screen -XS {{ env.PROVIDER_SERVICE_1 }} quit || true
+          screen -XS {{ env.PROVIDER_SERVICE_2 }} quit || true
           # consumer chains
           killall ${{ env.CONSUMER_CHAIN_BINARY }} || true
           killall ${{ env.CONSUMER_CHAIN_BINARY_2 }} || true
