verify values

diff --git a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
@@ -284,7 +284,23 @@ jobs:
           tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
           echo "[INFO]: Query staking validators"
           $CHAIN_BINARY --home $HOME_2 query staking validators
-
+      - name: Check validator set is 1
+        run: |
+          $CHAIN_BINARY --home $HOME_1 q comet-validator-set -o json | jq -r '.'
+          total_validator=$($CHAIN_BINARY --home $HOME_1 q comet-validator-set -o json | jq -r '.pagination.total')
+          if [ $total_validator != 1 ]
+          then
+            echo "[ERROR]: Unexpected number of validators $total_validator, expected 1"
+            exit 1
+          fi
+      - name: Check number of signatures
+        run: |
+          total_signatures=$(curl -s 127.0.0.1:$VAL1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
+          if [ $total_signatures != 1 ]
+          then
+            echo "[ERROR]: Unexpected number of validators $total_signatures, expected 1"
+            exit 1
+          fi
       - name: _Transactions verified> bank send, delegate, and withdraw rewards
         run: tests/stateful/test_tx.sh
       - name: Send funds to wallet 4
