test consensus

diff --git a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v21-stateful-steps.yml
@@ -482,7 +482,7 @@ jobs:
         run: |
           echo "Query current gov params"
           $CHAIN_BINARY --home $HOME_1 q gov params -o json | jq -r '.'
-      - name: _Pre-proposal Verify Gov params
+      - name: _Pre-proposal test current gov params
         run: |
           echo "Verify deposit is not burned when quorum is reached by voting no"
           starting_balance=$($CHAIN_BINARY --home $HOME_1 q bank balances $WALLET_1 -o json | jq -r '.balances[] | select (.denom == "uatom") | .amount')
@@ -553,6 +553,25 @@ jobs:
           else
             echo "PASSED!"
           fi
+      - name: _Pre-proposal test current consensus params
+        run: |
+          echo "[INFO]: Submit large proposal..."
+          json=$($CHAIN_BINARY tx gov submit-proposal templates/proposal-large-summary.json --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --from $WALLET_1 --keyring-backend test --home $HOME_1 --chain-id $CHAIN_ID -b sync -y -o json)
+          if [ $? -eq 0 ]
+          then
+            echo "[INFO]: Waiting for proposal to end"
+            sleep $VOTING_PERIOD
+            tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 1 10
+            # get tx hash
+            txhash=$(echo $json | jq -r '.txhash')
+            $CHAIN_BINARY --home $HOME_1 q tx $txhash
+            proposal_id=$($CHAIN_BINARY q tx $txhash --home $HOME_1 --output json | jq -r '.events[] | select(.type=="submit_proposal") | .attributes[] | select(.key=="proposal_id") | .value')
+            $CHAIN_BINARY --home $HOME_1 q gov proposal $proposal_id
+          else
+            echo "[ERROR]: Proposal did not go through"
+            exit 1
+          fi
+
       - name: Submit proposal to update modules params
         run: scripts/submit_proposal.sh templates/proposal-test-update-all-modules.json
       - name: _Verify consensus params prop is set
