rewards distribution

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -2290,9 +2290,11 @@
               $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
 
 
-          # - name: Register consumer reward denoms
-            # run: |
-          
+          - name: Register consumer reward denoms
+            run: |
+              source scripts/vars.sh  
+              source scripts/vars_changeover.sh
+              scripts/update_consumer_rewards channel-0              
           
             #     last_channel=$($CHAIN_BINARY q ibc channel channels -o json --home $HOME_1 | jq -r '.channels[-1].channel_id')
           #     echo "> Last channel: $last_channel"
@@ -2301,25 +2303,24 @@
           #     scripts/change_denoms.sh $denom_640
           #     $CHAIN_BINARY q provider registered-consumer-reward-denoms --home $HOME_1 -o json | jq '.'
 
-          # - name: _Consumer rewards distribution> ICS v6.4.0
-          #   run: |
-          #     last_channel=$($CHAIN_BINARY q ibc channel channels -o json --home $HOME_1 | jq -r '.channels[-1].channel_id')
-          #     ibc_denom=ibc/$(echo -n "transfer/${last_channel}/$CONSUMER_DENOM" | shasum -a 256 | cut -d ' ' -f1 | tr 'a-z' 'A-Z')
-          #     echo "> Denom: $ibc_denom"
-          #     echo "> Consumer rewards pool balances:"
-          #     $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $HOME_1 -o json | jq '.'
-          #     echo "> Val1 outstanding rewards:"
-          #     $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $HOME_1 -o json | jq '.'
-          #     val1_rewards=$(curl -s http://localhost:$VAL1_API_PORT/cosmos/distribution/v1beta1/validators/$VALOPER_1/outstanding_rewards | jq -r '.rewards.rewards')
-          #     echo "> val1_rewards: $val1_rewards"
-          #     val1_consumer_rewards=$(echo $val1_rewards | jq -r --arg DENOM "$ibc_denom" '.[] | select(.denom==$DENOM).amount')
-          #     echo "> val1_consumer_rewards: $val1_consumer_rewards"
-          #     if [ -z "$val1_consumer_rewards" ]; then
-          #       echo "FAIL: No consumer rewards distributed to val1."
-          #       exit 1
-          #     else
-          #       echo "PASS: Consumer rewards distributed to val1."
-          #     fi
+          - name: _Consumer rewards distribution> ICS v6.4.0
+            run: |
+              ibc_denom=ibc/$(echo -n transfer/channel-0/$CONSUMER_DENOM | shasum -a 256 | cut -d ' ' -f1 | tr '[a-z]' '[A-Z]')
+              echo "> Denom: $ibc_denom"
+              echo "> Consumer rewards pool balances:"
+              $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
+              echo "> Val1 outstanding rewards:"
+              $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
+              val1_rewards=$(curl -s http://localhost:$whale_api/cosmos/distribution/v1beta1/validators/$VALOPER_1/outstanding_rewards | jq -r '.rewards.rewards')
+              echo "> val1_rewards: $val1_rewards"
+              val1_consumer_rewards=$(echo $val1_rewards | jq -r --arg DENOM "$ibc_denom" '.[] | select(.denom==$DENOM).amount')
+              echo "> val1_consumer_rewards: $val1_consumer_rewards"
+              if [ -z "$val1_consumer_rewards" ]; then
+                echo "FAIL: No consumer rewards distributed to val1."
+                exit 1
+              else
+                echo "PASS: Consumer rewards distributed to val1."
+              fi
 
       # Test-12-ics-sovereign-new-connection:
       #   runs-on: ubuntu-24.04
