test tx

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -351,6 +351,50 @@ jobs:
           fi
       - name: _Transactions verified> bank send, delegate, and withdraw rewards
         run: tests/stateful/test_tx.sh
+      - name: _TX bank send
+        run: |
+          echo "Sending funds with tx bank send..."
+          txhash=$($CHAIN_BINARY tx bank send $WALLET_1 $WALLET_2 $VAL_STAKE_STEP$DENOM --home $HOME_1 --from $MONIKER_1 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
+          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
+          echo "Code is: $code"
+          if [ $code -ne 0 ]; then
+            echo "TX unsuccessful"
+            exit 1
+          fi
+      - name: _TX bank send
+        run: |
+          txhash=$($CHAIN_BINARY tx bank send $WALLET_1 $WALLET_2 $VAL_STAKE_STEP$DENOM --home $HOME_1 --from $MONIKER_1 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
+          echo "[INFO]: txhash: $txhash"
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
+          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
+          echo "[INFO]: Code is: $code"
+          if [ $code -ne 0 ]; then
+            echo "[ERROR]: TX unsuccessful"
+            exit 1
+          fi
+      - name: _TX delegate funds
+        run: |
+          txhash=$($CHAIN_BINARY tx staking delegate $VALOPER_1 $VAL_STAKE$DENOM --home $HOME_1 --from $MONIKER_2 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
+          echo "[INFO]: txhash: $txhash"
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
+          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
+          echo "[INFO]: Code is: $code"
+          if [ $code -ne 0 ]; then
+            echo "[ERROR]: TX unsuccessful"
+            exit 1
+          fi
+      - name: _TX distribution withdraw-rewards
+        run: |
+          txhash=$($CHAIN_BINARY tx distribution withdraw-rewards $VALOPER_1 --home $HOME_1 --from $MONIKER_2 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM --chain-id $CHAIN_ID -y -o json -b sync | jq '.txhash' | tr -d '"')
+          echo "[INFO]: txhash: $txhash"
+          tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 20
+          code=$($CHAIN_BINARY q tx $txhash -o json --home $HOME_1 | jq '.code')
+          echo "[INFO]: Code is: $code"
+          if [ $code -ne 0 ]; then
+            echo "[ERROR]: TX unsuccessful"
+            exit 1
+          fi
       - name: Send funds to wallet 4
         run: $CHAIN_BINARY tx bank send $WALLET_1 $WALLET_4 10000000$DENOM --home $HOME_1 --from $MONIKER_1 --keyring-backend test --gas auto --gas-prices $GAS_PRICES$DENOM --gas-adjustment $GAS_ADJUSTMENT --chain-id $CHAIN_ID -y -b sync
       - name: Wait for 1 block to pass
