update snapshot and gaia versions

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -338,12 +338,20 @@ jobs:
       - name: _Test bank multi-send to 500 wallets
         run : |
           source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 500 10 uatom 1 12000uatom
+          set +e
+          tests/stateful/test_multi-send_gas.sh 500 10 uatom 1 80000uatom
+          if [ $? -eq 0 ]
+          then
+              echo "[FAIL]: TX was successful"
+              exit 1
+          else
+            echo "[PASS]: TX was not successful"
+          fi
       - name: _Test bank multi-send to 501 wallets
         run : |
           source ~/env/bin/activate
           set +e
-          tests/stateful/test_multi-send_gas.sh 501 10 uatom 1 12000uatom
+          tests/stateful/test_multi-send_gas.sh 501 10 uatom 1 80000uatom
           if [ $? -eq 0 ]
           then
               echo "[FAIL]: TX was successful"
