remove consumer chain

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -580,122 +580,34 @@
               source scripts/vars.sh
               source scripts/vars_consumer_v701_two.sh
               tests/test_consumer_downtime.sh
+      
+          - name: _Remove consumer chain> ICS v4.0.0 chain 1
+            run: |
+              source scripts/vars.sh
+              source scripts/vars_consumer_v400_one.sh
+              echo "Consumer chains:"
+              $CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq '.'
+              consumer_id=$($CHAIN_BINARY q provider list-consumer-chains --home $whale_home -o json | jq --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).consumer_id')
+              echo "Removing v400-one (consumer_id = $consumer_id):"
+              txhash=$($CHAIN_BINARY tx provider remove-consumer $consumer_id -from $WALLET_1 --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home -o json | jq -r '.txhash')
+              sleep $(($COMMIT_TIMEOUT*2))
+              $CHAIN_BINARY q tx $txhash -o json | jq '.'
+              $CHAIN_BINARY q provider list-consumer-chains --home $whale_rpc -o json | jq '.'
+              phase=$($CHAIN_BINARY q provider list-consumer-chains --home $whale_rpc -o json | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id == $chain).phase')
+              if [[ "$phase" -eq "CONSUMER_PHASE_STOPPED" ]]; then
+                echo "PASS: Consumer chain was stopped."
+              else
+                echo "FAIL: Consumer chain was not stopped."
+                exit 1
+              fi
               
-          # - name: _Downtime test> val3 must not be jailed 
-          #   run: |
-          #     tests/test_validator_jailed.sh $VALOPER_3 null
-          #     $CHAIN_BINARY q provider list-consumer-chains -o json --home $HOME_1 | jq '.'
-          # - name: Stop validator services
-          #   env:
-          #     CONSUMER_SERVICE_2: v640-1-2.service
-          #     CONSUMER_SERVICE_3: v640-1-3.service
-          #     CONSUMER_ID: 4
-          #   run: |
-          #     $CHAIN_BINARY tx provider opt-out $CONSUMER_ID --from $WALLET_3 --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE$DENOM --home $HOME_1 -y
-          #     $CHAIN_BINARY q staking validators --home $HOME_1 -o json | jq '.'
-          #     sleep $(($COMMIT_TIMEOUT*30))
-          #     $CHAIN_BINARY q provider consumer-opted-in-validators $CONSUMER_ID --home $HOME_1
-          #     # $CHAIN_BINARY q provider consumer-opted-in-validators v640-one --home $HOME_1
-          #     sudo systemctl disable $CONSUMER_SERVICE_2 --now
-          #     sudo systemctl disable $CONSUMER_SERVICE_3 --now
-          #     sleep $(($COMMIT_TIMEOUT*30))
-          # - name: _Downtime test> val2 must be jailed - 1
-          #   run: |
-          #     tests/test_validator_jailed.sh $VALOPER_2 true
-          #     $CHAIN_BINARY q staking validators --home $HOME_1 -o json | jq '.'
-          # - name: _Downtime test> val3 must not be jailed 
-          #   run: |
-          #     tests/test_validator_jailed.sh $VALOPER_3 null
-          # - name: Unjail validator
-          #   env:
-          #     CONSUMER_SERVICE_2: v640-1-2.service
-          #   run: |
-          #     sudo systemctl enable $CONSUMER_SERVICE_2 --now
-          #     sleep $(($COMMIT_TIMEOUT*10))
-          #     $CHAIN_BINARY tx slashing unjail --from $WALLET_2 --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE$DENOM -y --home $HOME_1
-          #     sleep $(($COMMIT_TIMEOUT*2))
-          # - name: _Downtime test> val2 must not be jailed 
-          #   run: |
-          #     tests/test_validator_jailed.sh $VALOPER_2 null
-          # # - name: Change infraction parameter
-          # #   env:
-          # #     CONSUMER_ID: 0
-          # #   run: |
-          # #     scripts/update_consumer.sh
-          # - name: Stop validator services
-          #   env:
-          #     CONSUMER_SERVICE_2: v640-1-2.service
-          #   run: |
-          #     $CHAIN_BINARY q staking validators --home $HOME_1 -o json | jq '.'
-          #     sudo systemctl disable $CONSUMER_SERVICE_2 --now
-          #     sleep $(($COMMIT_TIMEOUT*30))
-          # - name: _Downtime test> val2 must be jailed - 2
-          #   run: |
-          #     tests/test_validator_jailed.sh $VALOPER_2 true
-          #     $CHAIN_BINARY q staking validators --home $HOME_1 -o json | jq '.'
-          # - name: Unjail validator
-          #   env:
-          #     CONSUMER_SERVICE_2: v640-1-2.service
-          #   run: |
-          #     sudo systemctl enable $CONSUMER_SERVICE_2 --now
-          #     sleep $(($COMMIT_TIMEOUT*10))
-          #     $CHAIN_BINARY tx slashing unjail --from $WALLET_2 --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE$DENOM -y --home $HOME_1
-          #     sleep $(($COMMIT_TIMEOUT*2))
-          # - name: _Downtime test> val2 must not be jailed 
-          #   run: |
-          #     tests/test_validator_jailed.sh $VALOPER_2 null
-          
-
-          # - name: _Remove consumer chain> ICS v4.5.0 chain 2
-          #   run: |
-          #     echo "Consumer chains:"
-          #     $CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq '.'
-          #     consumer_id=$($CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq -r '.chains[] | select(.chain_id == "v450-two").consumer_id')
-          #     echo "Removing v450-two (consumer_id = $consumer_id):"
-          #     $CHAIN_BINARY tx provider remove-consumer $consumer_id --from $WALLET_1 --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE$DENOM -y --home $HOME_1
-          #     sleep $(($COMMIT_TIMEOUT*2))
-          #     echo "Consumer chains:"
-          #     $CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq '.'
-          #     phase=$($CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq -r '.chains[] | select(.chain_id == "v450-two").phase')
-          #     if [[ "$phase" -eq "CONSUMER_PHASE_STOPPED" ]]; then
-          #       echo "PASS: Consumer chain was stopped."
-          #     else
-          #       echo "FAIL: Consumer chain was not stopped."
-          #       exit 1
-          #     fi
-          # - name: _Remove consumer chain> ICS v4.0.0 chain 1
-          #   run: |
-          #     echo "Consumer chains:"
-          #     $CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq '.'
-          #     consumer_id=$($CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq -r '.chains[] | select(.chain_id == "v400-one").consumer_id')
-          #     echo "Removing v400-one (consumer_id = $consumer_id):"
-  
-          #     jq -r --arg CONSUMER "$consumer_id" '.messages[0].consumer_id |= $CONSUMER' templates/proposal-remove-consumer.json > remove-consumer.json
-          #     jq '.' remove-consumer.json
-          #     txhash=$($CHAIN_BINARY tx gov submit-proposal remove-consumer.json --from $WALLET_1 --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE$DENOM -y --home $HOME_1 -o json | jq -r '.txhash')
-          #     sleep $(($COMMIT_TIMEOUT*2))
-          #     proposal_id=$($CHAIN_BINARY --output json q tx $txhash --home $HOME_1 | jq -r '.events[] | select(.type=="submit_proposal") | .attributes[] | select(.key=="proposal_id") | .value')
-          #     echo "Voting on consumer removal proposal $proposal_id."
-          #     $CHAIN_BINARY tx gov vote $proposal_id yes --from $WALLET_1 --gas auto --gas-prices 0.005$DENOM --gas-adjustment 3 --yes --home $HOME_1
-          #     sleep $(($COMMIT_TIMEOUT*2))
-          #     sleep $VOTING_PERIOD
-          #     echo "Consumer chains:"
-          #     $CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq '.'
-          #     phase=$($CHAIN_BINARY q provider list-consumer-chains --home $HOME_1 -o json | jq -r '.chains[] | select(.chain_id == "v400-one").phase')
-          #     if [[ "$phase" -eq "CONSUMER_PHASE_STOPPED" ]]; then
-          #       echo "PASS: Consumer chain was stopped."
-          #     else
-          #       echo "FAIL: Consumer chain was not stopped."
-          #       exit 1
-          #     fi
-              
-          - name: Test snapshot
+          - name: _Test consumer equivocation
             run: |
               export CHAIN_BINARY_URL=https://github.com/cosmos/gaia/releases/download/${{ matrix.start_version }}/gaiad-${{ matrix.start_version }}-linux-amd64  
               source scripts/vars.sh
               source scripts/vars_consumer_v400_one.sh
               tests/test_consumer_equivocation_legacy.sh
-          - name: Test light client attack
+          - name: _Test consumer light client attack
             run: |
               source scripts/vars.sh
               source scripts/vars_consumer_v400_one.sh
