fix liquid test

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -5068,85 +5068,85 @@
             run: |
               tests/test_pfm_transfers.sh
 
-          # - name: Set up happy path liquid accounts
-          #   run: |
-          #     source scripts/vars.sh
-          #     scripts/lsm_account_setup.sh
+          - name: Set up happy path liquid accounts
+            run: |
+              source scripts/vars.sh
+              scripts/lsm_account_setup.sh
 
-          # - name: Pre-upgrade x/liquid happy path
-          #   run: |
-          #     source scripts/vars.sh
-          #     tests/test_liquid_happy_path.sh
+          - name: Pre-upgrade x/liquid happy path
+            run: |
+              source scripts/vars.sh
+              tests/test_liquid_happy_path.sh
     
-          # - name: Tokenize with upgrade_wallet
-          #   run: |
-          #     source scripts/vars.sh
-          #     upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
-          #     echo "> Delegating."
-          #     $CHAIN_BINARY tx staking delegate $VALOPER_1 1000000uatom --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
-          #     sleep $(($COMMIT_TIMEOUT+2))
-          #     echo "> Tokenizing."
-          #     echo "> Command: $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
-          #     $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
-          #     sleep $(($COMMIT_TIMEOUT+2))
-          #     $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
+          - name: Tokenize with upgrade_wallet
+            run: |
+              source scripts/vars.sh
+              upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
+              echo "> Delegating."
+              $CHAIN_BINARY tx staking delegate $VALOPER_1 1000000uatom --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
+              sleep $(($COMMIT_TIMEOUT+2))
+              echo "> Tokenizing."
+              echo "> Command: $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
+              $CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 1000000$DENOM $upgrade_wallet --from upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
+              sleep $(($COMMIT_TIMEOUT+2))
+              $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
 
-          # - name: Redeem tokens with upgrade_wallet
-          #   run: |
-          #     source scripts/vars.sh
-          #     upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
-          #     $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     liquid_denom=$($CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq -r --arg valoper "$VALOPER_1" '.balances | map(select(.denom | startswith($valoper))) | .[-1].denom')
-          #     $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     starting_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
-          #     echo "> Denom: $liquid_denom"
-          #     echo "> Command: $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $whale_home -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
-          #     $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
-          #     sleep $(($COMMIT_TIMEOUT+2))
-          #     $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
-          #     ending_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
-          #     diff=$(echo "$ending_delegation_amount - $starting_delegation_amount" | bc)
-          #     echo "> Difference in delegation amount: $diff"
-          #     if [[ "$diff" == "1000000" ]]; then
-          #         echo "Token redemption succeeded."
-          #     else
-          #         echo "Token redemption failed."
-          #         exit 1
-          #     fi
+          - name: Redeem tokens with upgrade_wallet
+            run: |
+              source scripts/vars.sh
+              upgrade_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="upgrade_wallet").address')
+              $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
+              liquid_denom=$($CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq -r --arg valoper "$VALOPER_1" '.balances | map(select(.denom | startswith($valoper))) | .[-1].denom')
+              $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
+              starting_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
+              echo "> Denom: $liquid_denom"
+              echo "> Command: $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $whale_home -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home"
+              $CHAIN_BINARY tx liquid redeem-tokens 1000000$liquid_denom --from $upgrade_wallet -o json --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y --home $whale_home
+              sleep $(($COMMIT_TIMEOUT+2))
+              $CHAIN_BINARY q bank balances $upgrade_wallet --home $whale_home -o json | jq '.'
+              $CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq '.'
+              ending_delegation_amount=$($CHAIN_BINARY q staking delegations $upgrade_wallet --home $whale_home -o json | jq -r '.delegation_responses[0].balance.amount')
+              diff=$(echo "$ending_delegation_amount - $starting_delegation_amount" | bc)
+              echo "> Difference in delegation amount: $diff"
+              if [[ "$diff" == "1000000" ]]; then
+                  echo "Token redemption succeeded."
+              else
+                  echo "Token redemption failed."
+                  exit 1
+              fi
     
-          # - name: Set up vesting account
-          #   run: |
-          #     source scripts/vars.sh
-          #     echo "Creating vesting wallet..."
-          #     $CHAIN_BINARY keys add vesting --home $whale_home
-          #     vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
-          #     start_time=$(date +%s)
-          #     echo "start time: $start_time"
-          #     end_time=$(date -d '10 minutes'  +%s)
-          #     echo "end time: $end_time"
-          #     $CHAIN_BINARY tx vesting create-vesting-account \
-          #     $vesting_wallet $VESTING_AMOUNT$DENOM $end_time \
-          #     --from $WALLET_1 --home $whale_home \
-          #     --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y
-          #     sleep 1m
+          - name: Set up vesting account
+            run: |
+              source scripts/vars.sh
+              echo "Creating vesting wallet..."
+              $CHAIN_BINARY keys add vesting --home $whale_home
+              vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
+              start_time=$(date +%s)
+              echo "start time: $start_time"
+              end_time=$(date -d '10 minutes'  +%s)
+              echo "end time: $end_time"
+              $CHAIN_BINARY tx vesting create-vesting-account \
+              $vesting_wallet $VESTING_AMOUNT$DENOM $end_time \
+              --from $WALLET_1 --home $whale_home \
+              --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y
+              sleep 1m
     
-          #     echo "Saving vesting times..."
-          #     duration=$(echo "$end_time - $start_time" | bc -l)
-          #     echo "duration: $duration"
-          #     echo "vesting_start_time=$start_time" >> $GITHUB_ENV
-          #     echo "vesting_end_time=$end_time" >> $GITHUB_ENV
-          #     echo "vesting_duration=$duration" >> $GITHUB_ENV
+              echo "Saving vesting times..."
+              duration=$(echo "$end_time - $start_time" | bc -l)
+              echo "duration: $duration"
+              echo "vesting_start_time=$start_time" >> $GITHUB_ENV
+              echo "vesting_end_time=$end_time" >> $GITHUB_ENV
+              echo "vesting_duration=$duration" >> $GITHUB_ENV
   
-          # - name: Delegate with vesting wallet
-          #   run: |
-          #     source scripts/vars.sh
-          #     vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
-          #     $CHAIN_BINARY q bank spendable-balances $vesting_wallet --home $whale_home -o json | jq '.'
-          #     echo "Delegating from vesting wallet..."
-          #     $CHAIN_BINARY tx staking delegate $VALOPER_1 $VESTING_DELEGATED_AMOUNT$DENOM \
-          #     --from $vesting_wallet --home $whale_home \
-          #     --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y      
+          - name: Delegate with vesting wallet
+            run: |
+              source scripts/vars.sh
+              vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
+              $CHAIN_BINARY q bank spendable-balances $vesting_wallet --home $whale_home -o json | jq '.'
+              echo "Delegating from vesting wallet..."
+              $CHAIN_BINARY tx staking delegate $VALOPER_1 $VESTING_DELEGATED_AMOUNT$DENOM \
+              --from $vesting_wallet --home $whale_home \
+              --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y      
     
           # - name: Start host chain
           #   run: |
