add name to metadata field

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -165,140 +165,140 @@
               export MAX_PROVIDER_VALIDATORS=5
               scripts/add_consumer.sh
 
-          - name: Initialize consumer chain with ICS v6.4.0  
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh
-              export validator_count=12
-              export MAX_VALIDATORS=8
-              export MAX_PROVIDER_VALIDATORS=5
-              wget $CONSUMER_CHAIN_BINARY_URL -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY -q
-              chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY
-              scripts/setup_consumer.sh
-              sleep $(($COMMIT_TIMEOUT*4))
+          # - name: Initialize consumer chain with ICS v6.4.0  
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh
+          #     export validator_count=12
+          #     export MAX_VALIDATORS=8
+          #     export MAX_PROVIDER_VALIDATORS=5
+          #     wget $CONSUMER_CHAIN_BINARY_URL -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY -q
+          #     chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY
+          #     scripts/setup_consumer.sh
+          #     sleep $(($COMMIT_TIMEOUT*4))
 
-          - name: Spawn consumer chain v640-one
-            env:
-              PROVIDER_ICS: v6.4.0
-            run: |
-              source scripts/vars.sh  
-              source scripts/vars_consumer_v640_one.sh
-              export validator_count=12
-              export MAX_VALIDATORS=8
-              export MAX_PROVIDER_VALIDATORS=5
-              scripts/spawn_consumer.sh
-          - name: Start consumer chain v640-one
-            run: |
-              source scripts/vars.sh 
-              source scripts/vars_consumer_v640_one.sh
-              export validator_count=12
-              export MAX_VALIDATORS=8
-              export MAX_PROVIDER_VALIDATORS=5
-              ./start-$CONSUMER_CHAIN_ID.sh
-              sleep $(($COMMIT_TIMEOUT*3))
-              tail -n 100 ${consumer_log_prefix}$COUNT_WIDTH
-          - name: _Pre-upgrade consumer chain produces blocks> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars_consumer_v640_one.sh
-              export validator_count=12
-              export MAX_VALIDATORS=8
-              export MAX_PROVIDER_VALIDATORS=5
-              tests/test_block_production.sh 127.0.0.1 ${consumer_whale_rpc} 5
+          # - name: Spawn consumer chain v640-one
+          #   env:
+          #     PROVIDER_ICS: v6.4.0
+          #   run: |
+          #     source scripts/vars.sh  
+          #     source scripts/vars_consumer_v640_one.sh
+          #     export validator_count=12
+          #     export MAX_VALIDATORS=8
+          #     export MAX_PROVIDER_VALIDATORS=5
+          #     scripts/spawn_consumer.sh
+          # - name: Start consumer chain v640-one
+          #   run: |
+          #     source scripts/vars.sh 
+          #     source scripts/vars_consumer_v640_one.sh
+          #     export validator_count=12
+          #     export MAX_VALIDATORS=8
+          #     export MAX_PROVIDER_VALIDATORS=5
+          #     ./start-$CONSUMER_CHAIN_ID.sh
+          #     sleep $(($COMMIT_TIMEOUT*3))
+          #     tail -n 100 ${consumer_log_prefix}$COUNT_WIDTH
+          # - name: _Pre-upgrade consumer chain produces blocks> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars_consumer_v640_one.sh
+          #     export validator_count=12
+          #     export MAX_VALIDATORS=8
+          #     export MAX_PROVIDER_VALIDATORS=5
+          #     tests/test_block_production.sh 127.0.0.1 ${consumer_whale_rpc} 5
 
-          - name: Establish CCV channel for v640-one
-            run: |
-              source scripts/vars.sh  
-              source scripts/vars_consumer_v640_one.sh 
-              export validator_count=12
-              export MAX_VALIDATORS=8
-              export MAX_PROVIDER_VALIDATORS=5
-              client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
-              echo "Creating channel with Hermes..."
-              hermes create connection --a-chain $CONSUMER_CHAIN_ID --a-client 07-tendermint-0 --b-client $client_id
-              hermes create channel --a-chain $CONSUMER_CHAIN_ID --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
-              # sudo systemctl restart $RELAYER
-              tmux send-keys -t relayer C-c
-              scripts/start_relayer.sh
-              sleep $(($COMMIT_TIMEOUT*3))
+          # - name: Establish CCV channel for v640-one
+          #   run: |
+          #     source scripts/vars.sh  
+          #     source scripts/vars_consumer_v640_one.sh 
+          #     export validator_count=12
+          #     export MAX_VALIDATORS=8
+          #     export MAX_PROVIDER_VALIDATORS=5
+          #     client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
+          #     echo "Creating channel with Hermes..."
+          #     hermes create connection --a-chain $CONSUMER_CHAIN_ID --a-client 07-tendermint-0 --b-client $client_id
+          #     hermes create channel --a-chain $CONSUMER_CHAIN_ID --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
+          #     # sudo systemctl restart $RELAYER
+          #     tmux send-keys -t relayer C-c
+          #     scripts/start_relayer.sh
+          #     sleep $(($COMMIT_TIMEOUT*3))
 
-          - name: _Pre-upgrade CCV channel verified> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh  
-              export validator_count=12
-              export MAX_VALIDATORS=8
-              export MAX_PROVIDER_VALIDATORS=5
-              tests/test_ccv_channel.sh
-          - name: _Pre-upgrade IBC transfer successful> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh  
-              source scripts/vars_consumer_v640_one.sh
-              client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
-              connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
-              channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
-              tests/test_consumer_ibc_transfer.sh $channel_id channel-1
-              echo "> Save provider-side channel id to GH environment variable"
-              echo "TRANSFER_CHANNEL_ID=$channel_id" >> $GITHUB_ENV
+          # - name: _Pre-upgrade CCV channel verified> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh  
+          #     export validator_count=12
+          #     export MAX_VALIDATORS=8
+          #     export MAX_PROVIDER_VALIDATORS=5
+          #     tests/test_ccv_channel.sh
+          # - name: _Pre-upgrade IBC transfer successful> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh  
+          #     source scripts/vars_consumer_v640_one.sh
+          #     client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
+          #     connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
+          #     channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
+          #     tests/test_consumer_ibc_transfer.sh $channel_id channel-1
+          #     echo "> Save provider-side channel id to GH environment variable"
+          #     echo "TRANSFER_CHANNEL_ID=$channel_id" >> $GITHUB_ENV
     
               
-          - name: Trigger consumer rewards distribution> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh  
-              source scripts/vars_consumer_v640_one.sh
-              $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
-              echo "> Val1 outstanding rewards:"
-              $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
-              echo "> Send tx with high fees in consumer chain."
-              $CONSUMER_CHAIN_BINARY tx bank send consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc consumer1ay4dpm0kjmvtpug28vgw5w32yyjxa5spqtvan8 1$CONSUMER_DENOM \
-              --from consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc \
-              --gas auto --fees 1000000ucon \
-              --home $consumer_whale_home -o json -y | jq '.'
-              sleep $(($COMMIT_TIMEOUT*10))
-              $CONSUMER_CHAIN_BINARY tx bank send consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc consumer1ay4dpm0kjmvtpug28vgw5w32yyjxa5spqtvan8 1$CONSUMER_DENOM \
-              --from consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc \
-              --gas auto --fees 1000000ucons \
-              --home $consumer_whale_home -o json -y | jq '.'
-              sleep $(($COMMIT_TIMEOUT*20))
-              echo "> Balance in consumer chain recipient:"
-              $CONSUMER_CHAIN_BINARY q bank balances consumer1ay4dpm0kjmvtpug28vgw5w32yyjxa5spqtvan8 --home $consumer_whale_home -o json | jq '.'
-              echo "> Val1 outstanding rewards:"
-              $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
-              echo "> Rewards pool:"
-              $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
+          # - name: Trigger consumer rewards distribution> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh  
+          #     source scripts/vars_consumer_v640_one.sh
+          #     $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
+          #     echo "> Val1 outstanding rewards:"
+          #     $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
+          #     echo "> Send tx with high fees in consumer chain."
+          #     $CONSUMER_CHAIN_BINARY tx bank send consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc consumer1ay4dpm0kjmvtpug28vgw5w32yyjxa5spqtvan8 1$CONSUMER_DENOM \
+          #     --from consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc \
+          #     --gas auto --fees 1000000ucon \
+          #     --home $consumer_whale_home -o json -y | jq '.'
+          #     sleep $(($COMMIT_TIMEOUT*10))
+          #     $CONSUMER_CHAIN_BINARY tx bank send consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc consumer1ay4dpm0kjmvtpug28vgw5w32yyjxa5spqtvan8 1$CONSUMER_DENOM \
+          #     --from consumer1r5v5srda7xfth3hn2s26txvrcrntldju7725yc \
+          #     --gas auto --fees 1000000ucons \
+          #     --home $consumer_whale_home -o json -y | jq '.'
+          #     sleep $(($COMMIT_TIMEOUT*20))
+          #     echo "> Balance in consumer chain recipient:"
+          #     $CONSUMER_CHAIN_BINARY q bank balances consumer1ay4dpm0kjmvtpug28vgw5w32yyjxa5spqtvan8 --home $consumer_whale_home -o json | jq '.'
+          #     echo "> Val1 outstanding rewards:"
+          #     $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
+          #     echo "> Rewards pool:"
+          #     $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
 
-          - name: Add reward denom to allowlist> ICS v6.4.0 chain 1
-            run: |
-              source scripts/vars.sh  
-              source scripts/vars_consumer_v640_one.sh
-              client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
-              connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
-              channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
-              scripts/update_consumer_rewards.sh $channel_id
-              sleep $(($COMMIT_TIMEOUT*3))
+          # - name: Add reward denom to allowlist> ICS v6.4.0 chain 1
+          #   run: |
+          #     source scripts/vars.sh  
+          #     source scripts/vars_consumer_v640_one.sh
+          #     client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
+          #     connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
+          #     channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
+          #     scripts/update_consumer_rewards.sh $channel_id
+          #     sleep $(($COMMIT_TIMEOUT*3))
 
-          - name: _Consumer rewards distribution> ICS v6.4.0
-            run: |
-              source scripts/vars.sh
-              source scripts/vars_consumer_v640_one.sh
-              client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
-              connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
-              channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
-              ibc_denom=ibc/$(echo -n transfer/$channel_id/$CONSUMER_DENOM | shasum -a 256 | cut -d ' ' -f1 | tr '[a-z]' '[A-Z]')
-              echo "> Denom: $ibc_denom"
-              echo "> Consumer rewards pool balances:"
-              $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
-              echo "> Val1 outstanding rewards:"
-              $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
-              val1_rewards=$(curl -s http://localhost:$whale_api/cosmos/distribution/v1beta1/validators/$VALOPER_1/outstanding_rewards | jq -r '.rewards.rewards')
-              echo "> val1_rewards: $val1_rewards"
-              val1_consumer_rewards=$(echo $val1_rewards | jq -r --arg DENOM "$ibc_denom" '.[] | select(.denom==$DENOM).amount')
-              echo "> val1_consumer_rewards: $val1_consumer_rewards"
-              if [ -z "$val1_consumer_rewards" ]; then
-                echo "FAIL: No consumer rewards distributed to val1."
-                exit 1
-              else
-                echo "PASS: Consumer rewards distributed to val1."
-              fi            
+          # - name: _Consumer rewards distribution> ICS v6.4.0
+          #   run: |
+          #     source scripts/vars.sh
+          #     source scripts/vars_consumer_v640_one.sh
+          #     client_id=$($CHAIN_BINARY q provider list-consumer-chains -o json --home $whale_home | jq -r --arg chain "$CONSUMER_CHAIN_ID" '.chains[] | select(.chain_id==$chain).client_id')
+          #     connection_id=$($CHAIN_BINARY q ibc connection connections -o json --home $whale_home | jq -r --arg client "$client_id" '.connections[] | select(.client_id==$client).id')
+          #     channel_id=$($CHAIN_BINARY q ibc channel connections $connection_id -o json --home $whale_home | jq -r '.channels[] | select(.port_id=="transfer").channel_id')
+          #     ibc_denom=ibc/$(echo -n transfer/$channel_id/$CONSUMER_DENOM | shasum -a 256 | cut -d ' ' -f1 | tr '[a-z]' '[A-Z]')
+          #     echo "> Denom: $ibc_denom"
+          #     echo "> Consumer rewards pool balances:"
+          #     $CHAIN_BINARY q bank balances cosmos1ap0mh6xzfn8943urr84q6ae7zfnar48am2erhd --home $whale_home -o json | jq '.'
+          #     echo "> Val1 outstanding rewards:"
+          #     $CHAIN_BINARY q distribution validator-outstanding-rewards $VALOPER_1 --home $whale_home -o json | jq '.'
+          #     val1_rewards=$(curl -s http://localhost:$whale_api/cosmos/distribution/v1beta1/validators/$VALOPER_1/outstanding_rewards | jq -r '.rewards.rewards')
+          #     echo "> val1_rewards: $val1_rewards"
+          #     val1_consumer_rewards=$(echo $val1_rewards | jq -r --arg DENOM "$ibc_denom" '.[] | select(.denom==$DENOM).amount')
+          #     echo "> val1_consumer_rewards: $val1_consumer_rewards"
+          #     if [ -z "$val1_consumer_rewards" ]; then
+          #       echo "FAIL: No consumer rewards distributed to val1."
+          #       exit 1
+          #     else
+          #       echo "PASS: Consumer rewards distributed to val1."
+          #     fi            
 
           - name: Submit proposal to update provider params
             run: |
@@ -333,8 +333,10 @@
               $CHAIN_BINARY tx gov submit-proposal ics-proposal.json --home $whale_home --from proposer --gas 1000000 --gas-prices 0.005uatom --generate-only --chain-id testnet > unsigned-proposal.json
               echo "> Unsigned proposal:"
               jq '.' unsigned-proposal.json
+              echo "> Setting name in metadata"
+              jq '.body.messages[0].messages[0].metadata.name = "chain"' unsigned-proposal.json > unsigned-proposal-with-name.json
               echo "> Signing proposal"
-              $CHAIN_BINARY tx sign unsigned-proposal.json --from proposer --home $whale_home --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE --chain-id testnet -o json -y --output-document signed-ics-proposal.json
+              $CHAIN_BINARY tx sign unsigned-proposal-with-name.json --from proposer --home $whale_home --gas auto --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE --chain-id testnet -o json -y --output-document signed-ics-proposal.json
               echo "> Signed proposal:"
               jq '.' signed-ics-proposal.json
               echo "> Send funds from WALLET_1 to proposer"
