topn

diff --git a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-v20-stateful-steps.yml
@@ -71,6 +71,8 @@ jobs:
       CONSUMER_DENOM: ${{ vars.CONSUMER_DENOM }}
       CONSUMER_HOME_1: /home/runner/.cona1
       CONSUMER_HOME_2: /home/runner/.cona2
+      CONSUMERB_HOME_1: /home/runner/.conb1
+      CONSUMERB_HOME_2: /home/runner/.conb2
       STRIDE_SOV_CHAIN_BINARY_URL: https://github.com/hyphacoop/cosmos-builds/releases/download/stride-v11.0.0/stride-v11.0.0-linux-amd64
       STRIDE_CON_CHAIN_BINARY_URL: https://github.com/hyphacoop/cosmos-builds/releases/download/stride-v12.1.0/stride-v12.1.0-linux-amd64
       STRIDE_CHAIN_BINARY: strided
@@ -98,6 +100,18 @@ jobs:
       CON2_PPROF_PORT: 6164
       CONSUMER_SERVICE_1: cona1.service
       CONSUMER_SERVICE_2: cona2.service
+      CONB1_API_PORT: 25101
+      CONB1_GRPC_PORT: 26101
+      CONB1_RPC_PORT: 27101
+      CONB1_P2P_PORT: 28101
+      CONB1_PPROF_PORT: 6163
+      CONB2_API_PORT: 25102
+      CONB2_GRPC_PORT: 26102
+      CONB2_RPC_PORT: 27102
+      CONB2_P2P_PORT: 28102
+      CONB2_PPROF_PORT: 6164
+      CONSUMERB_SERVICE_1: conb1.service
+      CONSUMERB_SERVICE_2: conb2.service
       BASE_FEES: 30000
       HIGH_FEES: 25000
       GAS: auto
@@ -602,6 +616,106 @@ jobs:
       #     do
       #       sleep 1
       #     done
+      - name: Initialize consumer chain B with Interchain Security (Consumer) PSS
+        env:
+          CONSUMER_CHAIN_ID: consumerb
+          DOWNTIME_BLOCKS: 20
+          CONSUMER_NEW: true
+          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
+          CON1_API_PORT:
+          CONSUMER_HOME_1: ${{ vars.CONSUMERB_HOME_1 }}
+          CONSUMER_HOME_2: ${{ vars.CONSUMERB_HOME_2 }}
+          CON1_API_PORT: ${{ vars.CONB1_API_PORT }}
+          CON1_GRPC_PORT: ${{ vars.CONB1_GRPC_PORT }}
+          CON1_RPC_PORT: ${{ vars.CONB1_RPC_PORT }}
+          CON1_P2P_PORT: ${{ vars.CONB1_RPC_PORT }}
+          CON1_PPROF_PORT: ${{ vars.CONB1_PPROF_PORT }}
+          CON2_API_PORT: ${{ vars.CONB2_API_PORT }}
+          CON2_GRPC_PORT: ${{ vars.CONB2_GRPC_PORT }}
+          CON2_RPC_PORT: ${{ vars.CONB2_RPC_PORT }}
+          CON2_P2P_PORT: ${{ vars.CONB2_RPC_PORT }}
+          CON2_PPROF_PORT: ${{ vars.CONB2_PPROF_PORT }}
+          CONSUMER_SERVICE_1: conb1.service
+          CONSUMER_NEW: true
+          DOWNTIME_BLOCKS: 1000
+        run: scripts/stateful/init_consumer_2_vals.sh
+      - name: Launch opt-in consumer chain b
+        env:
+          CONSUMER_CHAIN_ID: consumerb
+          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
+          CONSUMER_HOME_1: ${{ vars.CONSUMERB_HOME_1 }}
+          CONSUMER_HOME_2: ${{ vars.CONSUMERB_HOME_2 }}
+          PSS_ENABLED: true
+          TOPN: 95
+        run: scripts/stateful/launch_consumer_2_vals_topn.sh v4.x
+      - name: _TopN consumer chain produces blocks val1> ICS v4.0.0
+        run: tests/test_block_production.sh 127.0.0.1 $CONB1_RPC_PORT 10
+      - name: _TopN consumer chain produces blocks val2> ICS v4.0.0
+        run: tests/test_block_production.sh 127.0.0.1 $CONB2_RPC_PORT 10
+      - name: Check block hashes on both consumerb nodes
+        run: |
+          latest_block=$($CONSUMER_CHAIN_BINARY --home $CONSUMERB_HOME_1 status | jq -r '.SyncInfo.latest_block_height')
+          echo "[INFO]: Block height is $latest_block"
+          hash_val1=$(curl -s 127.0.0.1:$CONB1_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
+          sleep 6
+          hash_val2=$(curl -s 127.0.0.1:$CONB2_RPC_PORT/block?height=$latest_block | jq -r '.result.block_id.hash')
+          echo "[INFO]: cona1 $hash_val1"
+          echo "[INFO]: cona2 $hash_val1"
+          if [ $hash_val1 != $hash_val2 ]
+          then
+            echo "[ERROR]: Block hash does not match. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
+            exit 1
+          else
+            echo "[INFO]: Block hash matches. VAL1 hash: $hash_val1 VAL2 hash: $hash_val2"
+          fi
+      - name: Check opt-in consumer tendermint validators
+        env:
+          CONSUMER_CHAIN_ID: consumerb
+        run: |
+          echo "[INFO]: $CONSUMER_CHAIN_BINARY q tendermint-validator-set"
+          $CONSUMER_CHAIN_BINARY --home $CONSUMER_HOME_1 q tendermint-validator-set -o json | jq -r '.'
+          # echo "[INFO]: $CHAIN_BINARY q provider has-to-validate"
+          # $CHAIN_BINARY --home $HOME_1 q provider has-to-validate -o json | jq -r '.'
+          echo "[INFO]: $CHAIN_BINARY q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID"
+          $CHAIN_BINARY --home $HOME_1 q provider consumer-opted-in-validators $CONSUMER_CHAIN_ID -o json | jq -r '.'
+      - name: Check number of signatures on consumera
+        run: |
+          total_signatures=$(curl -s 127.0.0.1:$CON1_RPC_PORT/block | jq -r '.result.block.last_commit.signatures | length')
+          if [ $total_signatures != 2 ]
+          then
+            echo "[ERROR]: Unexpected number of validators $total_signatures, expected 2"
+            exit 1
+          fi
+      - name: Establish CCV channel for consumer a
+        run: |
+          screen -XS hermes.service quit || true
+          killall hermes || true
+          sleep 1
+          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
+          hermes create connection --a-chain consumera --a-client 07-tendermint-0 --b-client $client_id
+          hermes create channel --a-chain consumera --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
+          echo "Starting Hermes"
+          screen -L -Logfile $HOME/artifact/hermes.service.log -S hermes.service -d -m bash $HOME/hermes.service.sh
+          # set screen to flush log to 0
+          screen -r hermes.service -p0 -X logfile flush 0
+          echo "Wait for hermes to start..."
+          ( tail -f -n0 $HOME/artifact/hermes.service.log & ) | grep -q "Hermes has started"
+          sleep 60
+      - name: _VSC successful> Interchain Security (Consumer) PSS
+        run: tests/stateful/test_ccv.sh
+      - name: _IBC transfer successful> Interchain Security (Consumer) PSS
+        env:
+          CONSUMER_CHAIN_ID: consumera
+        run: |
+          set -x
+          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
+          echo "Client ID: $client_id"
+          connection_id=$(hermes --json query client connections --chain $CHAIN_ID --client $client_id | jq -r '. | select(.result).result[]')
+          echo "Connection ID: $connection_id"
+          channel_id=$(hermes --json query connection channels --chain $CHAIN_ID --connection $connection_id | jq -r '. | select(.result).result[] | select(.port_id=="transfer").channel_id')
+          echo "Channel ID: $channel_id"
+          tests/stateful/test_consumer_ibc_transfer.sh $channel_id 2 $WALLET_1 $WALLET_CONSUMER_1
+          echo "CONSUMERA_CHAN_ID=$channel_id" >> $GITHUB_ENV
       - name: Set BlocksPerEpoch to 100
         run: scripts/submit_proposal.sh templates/proposal-blocks-per-epoch-100.json
       - name: Check BlocksPerEpoch is 100
