test max recipients

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -295,10 +295,22 @@ jobs:
         run : |
           source ~/env/bin/activate
           tests/stateful/test_multi-send_gas.sh 100 10 uatom 5 3000uatom
-      - name: _Test bank multi-send to 1000 wallets
+      - name: _Test bank multi-send to 500 wallets
         run : |
           source ~/env/bin/activate
-          tests/stateful/test_multi-send_gas.sh 1000 10 uatom 10 10000uatom
+          tests/stateful/test_multi-send_gas.sh 500 10 uatom 10 3000uatom
+      - name: _Test bank multi-send to 501 wallets
+        run : |
+          source ~/env/bin/activate
+          set +e
+          tests/stateful/test_multi-send_gas.sh 501 10 uatom 10 3000uatom
+          if [ $? -eq 0 ]
+          then
+              echo "[FAIL]: TX was successful"
+              exit 1
+          else
+            echo "[PASS]: TX was not successful"
+          fi
       - name: Query staking params
         run: |
           $CHAIN_BINARY --home $HOME_1 q staking params
