remove provider params

diff --git a/.github/workflows/upgrade-gaia-stateful-steps.yml b/.github/workflows/upgrade-gaia-stateful-steps.yml
--- a/.github/workflows/upgrade-gaia-stateful-steps.yml
+++ b/.github/workflows/upgrade-gaia-stateful-steps.yml
@@ -340,22 +340,22 @@ jobs:
         run: scripts/stateful/set_voting_period.sh templates/proposal-voting-period-60s.json
       - name: Query gov params time
         run: $CHAIN_BINARY --home $HOME_1 q gov params
-      - name: Query provider params
-        run: $CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.'
-      - name: Set BlocksPerEpoch to 1
-        run: scripts/submit_proposal.sh templates/proposal-blocks-per-epoch-1.json
-      - name: Query provider params
-        run: $CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.'
-      - name: Check BlocksPerEpoch is 1
-        run: |
-          set -e
-          BPE=$($CHAIN_BINARY --home $HOME_1 q provider params --output json |  jq -r '.blocks_per_epoch')
-          echo "BlocksPerEpoch is: $BPE"
-          if [ $BPE != 1 ]
-          then
-            echo "BlocksPerEpoch is not 1"
-            exit 1
-          fi
+      # - name: Query provider params
+      #   run: $CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.'
+      # - name: Set BlocksPerEpoch to 1
+      #   run: scripts/submit_proposal.sh templates/proposal-blocks-per-epoch-1.json
+      # - name: Query provider params
+      #   run: $CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.'
+      # - name: Check BlocksPerEpoch is 1
+      #   run: |
+      #     set -e
+      #     BPE=$($CHAIN_BINARY --home $HOME_1 q provider params --output json |  jq -r '.blocks_per_epoch')
+      #     echo "BlocksPerEpoch is: $BPE"
+      #     if [ $BPE != 1 ]
+      #     then
+      #       echo "BlocksPerEpoch is not 1"
+      #       exit 1
+      #     fi
       - name: Set slashing values
         run: |
           jq -r '.messages[0].params.signed_blocks_window="20"' templates/proposal-slashing-params.json > templates/proposal-slashing-params_signed_blocks_window.json
@@ -658,8 +658,8 @@ jobs:
           CHAIN_HOME: /home/runner/.val1
         run: tests/stateful/test_ica_controller.sh 
 
-      - name: Set BlocksPerEpoch to 100
-        run: scripts/submit_proposal.sh templates/proposal-blocks-per-epoch-100.json
+      # - name: Set BlocksPerEpoch to 100
+      #   run: scripts/submit_proposal.sh templates/proposal-blocks-per-epoch-100.json
       # - name: Check BlocksPerEpoch is 100
       #   run: |
       #     BPE=$($CHAIN_BINARY --home $HOME_1 q provider params --output json |  jq -r '.blocks_per_epoch')
@@ -948,66 +948,66 @@ jobs:
           else
             echo "PASSED!"
           fi
-      - name: _Verify provider params prop is set
-        env:
-          TEMPLATE_CLIENT_TRUSTING_PERIOD: "3600s"
-          TEMPLATE_CLIENT_UNBONDING_PERIOD: "1800s"
-          TRUSTING_PERIOD_FRACTION: "0.76"
-          CCV_TIMEOUT_PERIOD: "2419200s"
-          SLASH_METER_REPLENISH_PERIOD: "1800s"
-          SLASH_METER_REPLENISH_FRACTION: "0.01"
-          CONSUMER_REWARD_DENOM_REGISTRATION_FEE: "50000000"
-        run: |
-          echo "[INFO]: Current params:"
-          $CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.'
-          Q_TEMPLATE_CLIENT_TRUSTING_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.template_client.trusting_period') 
-          Q_TEMPLATE_CLIENT_UNBONDING_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.template_client.unbonding_period')
-          Q_TRUSTING_PERIOD_FRACTION=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.trusting_period_fraction')
-          Q_CCV_TIMEOUT_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.ccv_timeout_period')
-          Q_SLASH_METER_REPLENISH_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.slash_meter_replenish_period')
-          Q_SLASH_METER_REPLENISH_FRACTION=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.slash_meter_replenish_fraction')
-          Q_CONSUMER_REWARD_DENOM_REGISTRATION_FEE=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.consumer_reward_denom_registration_fee.amount')
-          if [ "$Q_TEMPLATE_CLIENT_TRUSTING_PERIOD" != "$TEMPLATE_CLIENT_TRUSTING_PERIOD" ]
-          then
-            echo "[ERROR]: TEMPLATE_CLIENT_TRUSTING_PERIOD does not match query: $TEMPLATE_CLIENT_TRUSTING_PERIOD $Q_TEMPLATE_CLIENT_TRUSTING_PERIOD"
-            error="1"
-          fi
-          if [ "$Q_TEMPLATE_CLIENT_UNBONDING_PERIOD" != "$TEMPLATE_CLIENT_UNBONDING_PERIOD" ]
-          then
-            echo "[ERROR]: TEMPLATE_CLIENT_UNBONDING_PERIOD does not match query: $TEMPLATE_CLIENT_UNBONDING_PERIOD $Q_TEMPLATE_CLIENT_UNBONDING_PERIOD"
-            error="1"
-          fi
-          if [ "$Q_TRUSTING_PERIOD_FRACTION" != "$TRUSTING_PERIOD_FRACTION" ]
-          then
-            echo "[ERROR]: TRUSTING_PERIOD_FRACTION does not match query: $TRUSTING_PERIOD_FRACTION $TRUSTING_PERIOD_FRACTION"
-            error="1"
-          fi
-          if [ "$Q_CCV_TIMEOUT_PERIOD" != "$CCV_TIMEOUT_PERIOD" ]
-          then
-            echo "[ERROR]: CCV_TIMEOUT_PERIOD does not match query: $CCV_TIMEOUT_PERIOD $Q_CCV_TIMEOUT_PERIOD"
-            error="1"
-          fi
-          if [ "$Q_SLASH_METER_REPLENISH_PERIOD" != "$SLASH_METER_REPLENISH_PERIOD" ]
-          then
-            echo "[ERROR]: SLASH_METER_REPLENISH_PERIOD does not match query: $SLASH_METER_REPLENISH_PERIOD $Q_SLASH_METER_REPLENISH_PERIOD"
-            error="1"
-          fi
-          if [ "$Q_SLASH_METER_REPLENISH_FRACTION" != "$SLASH_METER_REPLENISH_FRACTION" ]
-          then
-            echo "[ERROR]: SLASH_METER_REPLENISH_FRACTION does not match query: $SLASH_METER_REPLENISH_FRACTION $Q_SLASH_METER_REPLENISH_FRACTION"
-            error="1"
-          fi
-          if [ "$Q_CONSUMER_REWARD_DENOM_REGISTRATION_FEE" != "$CONSUMER_REWARD_DENOM_REGISTRATION_FEE" ]
-          then
-            echo "[ERROR]: CONSUMER_REWARD_DENOM_REGISTRATION_FEE does not match query: $CONSUMER_REWARD_DENOM_REGISTRATION_FEE $Q_CONSUMER_REWARD_DENOM_REGISTRATION_FEE"
-            error="1"
-          fi
-          if [ "$error" == "1" ]
-          then
-            exit 1
-          else
-            echo "PASSED!"
-          fi
+      # - name: _Verify provider params prop is set
+      #   env:
+      #     TEMPLATE_CLIENT_TRUSTING_PERIOD: "3600s"
+      #     TEMPLATE_CLIENT_UNBONDING_PERIOD: "1800s"
+      #     TRUSTING_PERIOD_FRACTION: "0.76"
+      #     CCV_TIMEOUT_PERIOD: "2419200s"
+      #     SLASH_METER_REPLENISH_PERIOD: "1800s"
+      #     SLASH_METER_REPLENISH_FRACTION: "0.01"
+      #     CONSUMER_REWARD_DENOM_REGISTRATION_FEE: "50000000"
+      #   run: |
+      #     echo "[INFO]: Current params:"
+      #     $CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.'
+      #     Q_TEMPLATE_CLIENT_TRUSTING_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.template_client.trusting_period') 
+      #     Q_TEMPLATE_CLIENT_UNBONDING_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.template_client.unbonding_period')
+      #     Q_TRUSTING_PERIOD_FRACTION=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.trusting_period_fraction')
+      #     Q_CCV_TIMEOUT_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.ccv_timeout_period')
+      #     Q_SLASH_METER_REPLENISH_PERIOD=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.slash_meter_replenish_period')
+      #     Q_SLASH_METER_REPLENISH_FRACTION=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.slash_meter_replenish_fraction')
+      #     Q_CONSUMER_REWARD_DENOM_REGISTRATION_FEE=$($CHAIN_BINARY --home $HOME_1 q provider params -o json | jq -r '.consumer_reward_denom_registration_fee.amount')
+      #     if [ "$Q_TEMPLATE_CLIENT_TRUSTING_PERIOD" != "$TEMPLATE_CLIENT_TRUSTING_PERIOD" ]
+      #     then
+      #       echo "[ERROR]: TEMPLATE_CLIENT_TRUSTING_PERIOD does not match query: $TEMPLATE_CLIENT_TRUSTING_PERIOD $Q_TEMPLATE_CLIENT_TRUSTING_PERIOD"
+      #       error="1"
+      #     fi
+      #     if [ "$Q_TEMPLATE_CLIENT_UNBONDING_PERIOD" != "$TEMPLATE_CLIENT_UNBONDING_PERIOD" ]
+      #     then
+      #       echo "[ERROR]: TEMPLATE_CLIENT_UNBONDING_PERIOD does not match query: $TEMPLATE_CLIENT_UNBONDING_PERIOD $Q_TEMPLATE_CLIENT_UNBONDING_PERIOD"
+      #       error="1"
+      #     fi
+      #     if [ "$Q_TRUSTING_PERIOD_FRACTION" != "$TRUSTING_PERIOD_FRACTION" ]
+      #     then
+      #       echo "[ERROR]: TRUSTING_PERIOD_FRACTION does not match query: $TRUSTING_PERIOD_FRACTION $TRUSTING_PERIOD_FRACTION"
+      #       error="1"
+      #     fi
+      #     if [ "$Q_CCV_TIMEOUT_PERIOD" != "$CCV_TIMEOUT_PERIOD" ]
+      #     then
+      #       echo "[ERROR]: CCV_TIMEOUT_PERIOD does not match query: $CCV_TIMEOUT_PERIOD $Q_CCV_TIMEOUT_PERIOD"
+      #       error="1"
+      #     fi
+      #     if [ "$Q_SLASH_METER_REPLENISH_PERIOD" != "$SLASH_METER_REPLENISH_PERIOD" ]
+      #     then
+      #       echo "[ERROR]: SLASH_METER_REPLENISH_PERIOD does not match query: $SLASH_METER_REPLENISH_PERIOD $Q_SLASH_METER_REPLENISH_PERIOD"
+      #       error="1"
+      #     fi
+      #     if [ "$Q_SLASH_METER_REPLENISH_FRACTION" != "$SLASH_METER_REPLENISH_FRACTION" ]
+      #     then
+      #       echo "[ERROR]: SLASH_METER_REPLENISH_FRACTION does not match query: $SLASH_METER_REPLENISH_FRACTION $Q_SLASH_METER_REPLENISH_FRACTION"
+      #       error="1"
+      #     fi
+      #     if [ "$Q_CONSUMER_REWARD_DENOM_REGISTRATION_FEE" != "$CONSUMER_REWARD_DENOM_REGISTRATION_FEE" ]
+      #     then
+      #       echo "[ERROR]: CONSUMER_REWARD_DENOM_REGISTRATION_FEE does not match query: $CONSUMER_REWARD_DENOM_REGISTRATION_FEE $Q_CONSUMER_REWARD_DENOM_REGISTRATION_FEE"
+      #       error="1"
+      #     fi
+      #     if [ "$error" == "1" ]
+      #     then
+      #       exit 1
+      #     else
+      #       echo "PASSED!"
+      #     fi
       - name: _Verify staking params prop is set
         env:
           UNBONDING_TIME: "240h0m0s"
