enable vesting for liquid staking

diff --git a/.github/workflows/upgrade-gaia-fresh-state.yml b/.github/workflows/upgrade-gaia-fresh-state.yml
--- a/.github/workflows/upgrade-gaia-fresh-state.yml
+++ b/.github/workflows/upgrade-gaia-fresh-state.yml
@@ -1656,160 +1656,170 @@
           #     echo "TRANSFER_CHANNEL_ID=$channel_id" >> $GITHUB_ENV
           #     tests/test_consumer_ibc_transfer.sh $channel_id channel-1
     
-      # Test-07-vesting-liquid-staking:
-      #   runs-on: ubuntu-24.04
-      #   needs: set-versions
-      #   strategy:
-      #     matrix:
-      #       start_version: [ "${{ needs.set-versions.outputs.start_version }}" ]
-      #       target_version: [ "${{ needs.set-versions.outputs.target_version }}" ]
-      #       upgrade_name: [ "${{ needs.set-versions.outputs.upgrade_name }}" ]
-      #     fail-fast: false
-      #   env:
-      #     COSMOVISOR: false
-      #     BINARY_SOURCE: ${{ needs.set-versions.outputs.binary_source }}
-      #     VESTING_AMOUNT: 110000000
-      #     VESTING_DELEGATED_AMOUNT: 100000000
-      #   steps:
-      #     - name: Update PATH
-      #       run: |
-      #         mkdir -p $HOME/go/bin
-      #         echo "$HOME/go/bin" >> $GITHUB_PATH
-      #         echo "$HOME/.hermes" >> $GITHUB_PATH
-      #         echo "$HOME/.relayer" >> $GITHUB_PATH
-      #     - name: Bypass the grub-efi-amd64-signed package
-      #       run: sudo apt-mark hold grub-efi-amd64-signed
-      #     - name: Check out repository code
-      #       uses: actions/checkout@v6
-      #     - name: Set up Python
-      #       uses: actions/setup-python@v6
-      #       with:
-      #         python-version: '3.11'
-      #     - name: Install dependencies
-      #       run: |
-      #         python -m pip install --upgrade pip
-      #         python -m pip install toml-cli
+      Test-07-vesting-liquid-staking:
+        runs-on: ubuntu-24.04
+        needs: set-versions
+        strategy:
+          matrix:
+            start_version: [ "${{ needs.set-versions.outputs.start_version }}" ]
+            target_version: [ "${{ needs.set-versions.outputs.target_version }}" ]
+            upgrade_name: [ "${{ needs.set-versions.outputs.upgrade_name }}" ]
+          fail-fast: false
+        env:
+          COSMOVISOR: false
+          BINARY_SOURCE: ${{ needs.set-versions.outputs.binary_source }}
+          VESTING_AMOUNT: 110000000
+          VESTING_DELEGATED_AMOUNT: 100000000
+        steps:
+          - name: Update PATH
+            run: |
+              mkdir -p $HOME/go/bin
+              echo "$HOME/go/bin" >> $GITHUB_PATH
+              echo "$HOME/.hermes" >> $GITHUB_PATH
+              echo "$HOME/.relayer" >> $GITHUB_PATH
+          - name: Bypass the grub-efi-amd64-signed package
+            run: sudo apt-mark hold grub-efi-amd64-signed
+          - name: Check out repository code
+            uses: actions/checkout@v6
+          - name: Set up Python
+            uses: actions/setup-python@v6
+            with:
+              python-version: '3.11'
+          - name: Install dependencies
+            run: |
+              python -m pip install --upgrade pip
+              python -m pip install toml-cli
 
-      #     - name: Start chain
-      #       run: |
-      #         export CHAIN_BINARY_URL=https://github.com/cosmos/gaia/releases/download/${{ matrix.start_version }}/gaiad-${{ matrix.start_version }}-linux-amd64  
-      #         source scripts/vars.sh
-      #         scripts/setup.sh
-      #         ./$START_SCRIPT
-      #         sleep $(($COMMIT_TIMEOUT*2))
-      #         tail -n 100 $whale_log
-      #         scripts/wait_for_block.sh $whale_rpc 3
+          - name: Start chain
+            run: |
+              export CHAIN_BINARY_URL=https://github.com/cosmos/gaia/releases/download/${{ matrix.start_version }}/gaiad-${{ matrix.start_version }}-linux-amd64  
+              source scripts/vars.sh
+              scripts/setup.sh
+              ./$START_SCRIPT
+              sleep $(($COMMIT_TIMEOUT*2))
+              tail -n 100 $whale_log
+              scripts/wait_for_block.sh $whale_rpc 3
 
-      #     - name: Set up vesting account
-      #       run: |
-      #         source scripts/vars.sh
-      #         echo "Creating vesting wallet..."
-      #         $CHAIN_BINARY keys add vesting --home $whale_home
-      #         vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
-      #         start_time=$(date +%s)
-      #         echo "start time: $start_time"
-      #         end_time=$(date -d '10 minutes'  +%s)
-      #         echo "end time: $end_time"
-      #         $CHAIN_BINARY tx vesting create-vesting-account \
-      #         $vesting_wallet $VESTING_AMOUNT$DENOM $end_time \
-      #         --from $WALLET_1 --home $whale_home \
-      #         --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y
-      #         sleep 1m
+          - name: Set up vesting account
+            run: |
+              source scripts/vars.sh
+              echo "Creating vesting wallet..."
+              $CHAIN_BINARY keys add vesting --home $whale_home
+              vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
+              start_time=$(date +%s)
+              echo "start time: $start_time"
+              end_time=$(date -d '10 minutes'  +%s)
+              echo "end time: $end_time"
+              $CHAIN_BINARY tx vesting create-vesting-account \
+              $vesting_wallet $VESTING_AMOUNT$DENOM $end_time \
+              --from $WALLET_1 --home $whale_home \
+              --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y
+              sleep 1m
     
-      #         echo "Saving vesting times..."
-      #         duration=$(echo "$end_time - $start_time" | bc -l)
-      #         echo "duration: $duration"
-      #         echo "vesting_start_time=$start_time" >> $GITHUB_ENV
-      #         echo "vesting_end_time=$end_time" >> $GITHUB_ENV
-      #         echo "vesting_duration=$duration" >> $GITHUB_ENV
+              echo "Saving vesting times..."
+              duration=$(echo "$end_time - $start_time" | bc -l)
+              echo "duration: $duration"
+              echo "vesting_start_time=$start_time" >> $GITHUB_ENV
+              echo "vesting_end_time=$end_time" >> $GITHUB_ENV
+              echo "vesting_duration=$duration" >> $GITHUB_ENV
     
-      #     - name: Delegate with vesting wallet
-      #       run: |
-      #         source scripts/vars.sh
-      #         vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
-      #         $CHAIN_BINARY q bank spendable-balances $vesting_wallet --home $whale_home -o json | jq '.'
-      #         echo "Delegating from vesting wallet..."
-      #         $CHAIN_BINARY tx staking delegate $VALOPER_1 $VESTING_DELEGATED_AMOUNT$DENOM \
-      #         --from $vesting_wallet --home $whale_home \
-      #         --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y      
+          - name: Delegate with vesting wallet
+            run: |
+              source scripts/vars.sh
+              vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
+              $CHAIN_BINARY q bank spendable-balances $vesting_wallet --home $whale_home -o json | jq '.'
+              echo "Delegating from vesting wallet..."
+              $CHAIN_BINARY tx staking delegate $VALOPER_1 $VESTING_DELEGATED_AMOUNT$DENOM \
+              --from $vesting_wallet --home $whale_home \
+              --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y      
     
-      #     - name: Upgrade to v27.0.0
-      #       env:
-      #         TARGET_VERSION: v27.0.0
-      #         STAKING_OPERATIONS: false
-      #       run: |
-      #         export DOWNLOAD_URL=https://github.com/cosmos/gaia/releases/download/${TARGET_VERSION}/gaiad-${TARGET_VERSION}-linux-amd64  
-      #         source scripts/vars.sh
-      #         scripts/upgrade.sh $TARGET_VERSION
+          - name: Upgrade to v27.0.0
+            env:
+              TARGET_VERSION: v27.0.0
+              STAKING_OPERATIONS: false
+            run: |
+              export DOWNLOAD_URL=https://github.com/cosmos/gaia/releases/download/${TARGET_VERSION}/gaiad-${TARGET_VERSION}-linux-amd64  
+              source scripts/vars.sh
+              scripts/upgrade.sh $TARGET_VERSION
 
-      #     - name: Upgrade to v27.1.0
-      #       env:
-      #         TARGET_VERSION: v27.1.0
-      #         STAKING_OPERATIONS: false
-      #       run: |
-      #         export DOWNLOAD_URL=https://github.com/cosmos/gaia/releases/download/${TARGET_VERSION}/gaiad-${TARGET_VERSION}-linux-amd64  
-      #         source scripts/vars.sh
-      #         scripts/upgrade.sh $TARGET_VERSION
+          - name: Upgrade to v27.1.0
+            env:
+              TARGET_VERSION: v27.1.0
+              STAKING_OPERATIONS: false
+            run: |
+              export DOWNLOAD_URL=https://github.com/cosmos/gaia/releases/download/${TARGET_VERSION}/gaiad-${TARGET_VERSION}-linux-amd64  
+              source scripts/vars.sh
+              scripts/upgrade.sh $TARGET_VERSION
+              
+          - name: Upgrade to v27.2.0
+            env:
+              TARGET_VERSION: v27.2.0
+              STAKING_OPERATIONS: false
+            run: |
+              export DOWNLOAD_URL=https://github.com/cosmos/gaia/releases/download/${TARGET_VERSION}/gaiad-${TARGET_VERSION}-linux-amd64  
+              source scripts/vars.sh
+              scripts/upgrade.sh $TARGET_VERSION
 
-      #     - name: Test software upgrade
-      #       env:
-      #         TARGET_VERSION: ${{ matrix.target_version }}
-      #         DOWNLOAD_URL: https://github.com/cosmos/gaia/releases/download/${{ matrix.target_version }}/gaiad-${{ matrix.target_version }}-linux-amd64
-      #       run: |
-      #         source scripts/vars.sh
-      #         scripts/upgrade.sh ${{ matrix.upgrade_name }}
+          - name: Test software upgrade
+            env:
+              TARGET_VERSION: ${{ matrix.target_version }}
+              # DOWNLOAD_URL: https://github.com/cosmos/gaia/releases/download/${{ matrix.target_version }}/gaiad-${{ matrix.target_version }}-linux-amd64
+            run: |
+              source scripts/vars.sh
+              export DOWNLOAD_URL=https://github.com/hyphacoop/cosmos-builds/releases/download/v28-preview/gaiad
+              scripts/upgrade.sh ${{ matrix.upgrade_name }}
           
-      #     - name: _Blocks produced after upgrade
-      #       run: |
-      #         source scripts/vars.sh
-      #         tests/test_block_production.sh 127.0.0.1 $whale_rpc 5
+          - name: _Blocks produced after upgrade
+            run: |
+              source scripts/vars.sh
+              tests/test_block_production.sh 127.0.0.1 $whale_rpc 5
     
-      #     - name: Tokenize with vesting wallet
-      #       run: |
-      #         source scripts/vars.sh
-      #         vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
-      #         $CHAIN_BINARY q staking delegations $vesting_wallet --home $whale_home -o json | jq '.'
+          - name: Tokenize with vesting wallet
+            run: |
+              source scripts/vars.sh
+              vesting_wallet=$($CHAIN_BINARY keys list --home $whale_home --output json | jq -r '.[] | select(.name=="vesting").address')
+              $CHAIN_BINARY q staking delegations $vesting_wallet --home $whale_home -o json | jq '.'
   
-      #         echo "vesting_start_time = $vesting_start_time"
-      #         echo "vesting_end_time = $vesting_end_time"
-      #         echo "vesting_duration = $vesting_duration"
+              echo "vesting_start_time = $vesting_start_time"
+              echo "vesting_end_time = $vesting_end_time"
+              echo "vesting_duration = $vesting_duration"
     
-      #         echo "Calculating vested delegation..."
-      #         current_epoch=$(date +%s)
-      #         echo "epoch: $current_epoch"
-      #         elapsed_time=$(echo "$current_epoch - $vesting_start_time" | bc)
-      #         echo "elapsed_time: $elapsed_time"
-      #         vested_ratio=$(echo "$elapsed_time / $vesting_duration" | bc -l)
-      #         echo "vested ratio: $vested_ratio"
-      #         vested_amount=$(echo "($vested_ratio * $VESTING_DELEGATED_AMOUNT)/1" | bc)
-      #         echo "vested amount: $vested_amount"
+              echo "Calculating vested delegation..."
+              current_epoch=$(date +%s)
+              echo "epoch: $current_epoch"
+              elapsed_time=$(echo "$current_epoch - $vesting_start_time" | bc)
+              echo "elapsed_time: $elapsed_time"
+              vested_ratio=$(echo "$elapsed_time / $vesting_duration" | bc -l)
+              echo "vested ratio: $vested_ratio"
+              vested_amount=$(echo "($vested_ratio * $VESTING_DELEGATED_AMOUNT)/1" | bc)
+              echo "vested amount: $vested_amount"
     
-      #         txhash=$($CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 100000$DENOM $vesting_wallet --from $vesting_wallet --home $whale_home --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y -o json | jq -r '.txhash')
-      #         echo "txhash: $txhash"
+              txhash=$($CHAIN_BINARY tx liquid tokenize-share $VALOPER_1 100000$DENOM $vesting_wallet --from $vesting_wallet --home $whale_home --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --gas-prices $GAS_PRICE -y -o json | jq -r '.txhash')
+              echo "txhash: $txhash"
     
-      #         sleep $COMMIT_TIMEOUT
-      #         $CHAIN_BINARY q bank balances $vesting_wallet --home $whale_home -o json | jq -r '.balances[] | select(.denom == "cosmosvaloper1r5v5srda7xfth3hn2s26txvrcrntldju7lnwmv/1")'
-      #         liquid_tokens=$($CHAIN_BINARY q bank balances $vesting_wallet --home $whale_home -o json | jq -r '.balances[] | select(.denom == "cosmosvaloper1r5v5srda7xfth3hn2s26txvrcrntldju7lnwmv/1").amount')
-      #         echo "liquid tokens: $liquid_tokens"
-      #         if [[ "$liquid_tokens" -gt "0" ]]; then
-      #           echo "PASS: Greater than zero amount in liquid tokens balance."
-      #         else
-      #           echo "FAIL: No liquid tokens balance."
-      #           exit 1
-      #         fi
+              sleep $COMMIT_TIMEOUT
+              $CHAIN_BINARY q bank balances $vesting_wallet --home $whale_home -o json | jq -r '.balances[] | select(.denom == "cosmosvaloper1r5v5srda7xfth3hn2s26txvrcrntldju7lnwmv/1")'
+              liquid_tokens=$($CHAIN_BINARY q bank balances $vesting_wallet --home $whale_home -o json | jq -r '.balances[] | select(.denom == "cosmosvaloper1r5v5srda7xfth3hn2s26txvrcrntldju7lnwmv/1").amount')
+              echo "liquid tokens: $liquid_tokens"
+              if [[ "$liquid_tokens" -gt "0" ]]; then
+                echo "PASS: Greater than zero amount in liquid tokens balance."
+              else
+                echo "FAIL: No liquid tokens balance."
+                exit 1
+              fi
 
-      #     - name: _Transactions verified> bank send, delegate, and withdraw rewards
-      #       run: |
-      #         source scripts/vars.sh
-      #         tests/test_tx.sh
-      #     - name: _API endpoints check
-      #       run: |
-      #         source scripts/vars.sh
-      #         tests/test_endpoints_api.sh localhost $whale_api
-      #     - name: _RPC endpoints check
-      #       run: |
-      #         source scripts/vars.sh
-      #         tests/test_endpoints_rpc.sh localhost $whale_rpc
+          - name: _Transactions verified> bank send, delegate, and withdraw rewards
+            run: |
+              source scripts/vars.sh
+              tests/test_tx.sh
+          - name: _API endpoints check
+            run: |
+              source scripts/vars.sh
+              tests/test_endpoints_api.sh localhost $whale_api
+          - name: _RPC endpoints check
+            run: |
+              source scripts/vars.sh
+              tests/test_endpoints_rpc.sh localhost $whale_rpc
 
       # Test-08-ICA-controller:
       #   runs-on: ubuntu-24.04
